// meanings.js
// Plain-language, human meanings for each verse — written so the heart of the
// verse lands in seconds, not lost in theology or translation. Hand-written for
// a growing batch; every other verse falls back to a warm topic-based line so
// nothing is ever blank. Grown in batches, like the verse database.

const MEANINGS = {
  // ---- Bible ----
  "Genesis 1:27": "You carry something of God in you — your life has built-in worth and dignity.",
  "Genesis 28:15": "Wherever you go, you're watched over — you are not walking this road unaccompanied.",
  "Exodus 14:14": "You don't have to fight every battle yourself; sometimes the bravest move is to stay calm and trust.",
  "Deuteronomy 6:5": "Love God with everything you are — let that love steady and center your whole life.",
  "Deuteronomy 31:6": "Whatever you're walking into, you're not walking in alone — choose courage over fear.",
  "Joshua 1:9": "Be brave and keep going; you are accompanied every single step, wherever you go.",
  "1 Samuel 16:7": "You're seen for who you really are inside — not the surface others judge.",
  "1 Chronicles 16:11": "When you feel drained, turn toward God — that's where strength keeps getting refilled.",
  "Psalm 23:1": "You're cared for; you can stop striving for 'enough' — you're already provided for.",
  "Psalm 23:4": "Even in your darkest stretch you're not alone, so fear loses its grip.",
  "Psalm 27:1": "With God as your light, nothing left is big enough to truly fear.",
  "Psalm 34:8": "Try trusting God for yourself — you'll find, first-hand, that he is good.",
  "Psalm 34:18": "When your heart is broken, you are not abandoned — comfort is close.",
  "Psalm 37:4": "Delight in what's good, and your deepest desires get shaped and satisfied.",
  "Psalm 46:1": "When trouble hits, you have a safe place and a present help — right now.",
  "Psalm 46:10": "Pause. Breathe. You don't have to control everything — let peace return.",
  "Psalm 55:22": "Hand the weight over — you were never meant to carry it all alone.",
  "Psalm 118:24": "Today is a gift; choose to find joy in it rather than wait for a better one.",
  "Psalm 119:105": "You don't need the whole road lit — just enough light for the next step.",
  "Psalm 121:1-2": "When you don't know where help will come from, look up — help is on its way.",
  "Psalm 139:14": "You are wonderfully made on purpose — not a mistake, not an accident.",
  "Psalm 147:3": "Your wounds are not ignored; there is healing for the broken places.",
  "Proverbs 3:5-6": "Stop over-analyzing; trust, take the next step, and the path will straighten out.",
  "Proverbs 4:23": "Guard your heart — what you let in quietly shapes the life that flows out.",
  "Proverbs 15:1": "A soft answer cools things down; gentleness is strength, not weakness.",
  "Proverbs 19:21": "Make your plans, but stay open — a bigger purpose is at work.",
  "Isaiah 40:31": "Rest and hope refill your strength — you'll rise again, not run out.",
  "Isaiah 41:10": "Don't be afraid — you are held, strengthened, and helped through this.",
  "Isaiah 43:2": "When you go through deep waters, they won't overwhelm you — you're accompanied.",
  "Jeremiah 29:11": "Your story isn't over; a future and a hope are being written for you.",
  "Lamentations 3:22-23": "However rough yesterday was, mercy is brand new this morning.",
  "Micah 6:8": "Live simply and well: be fair, be kind, and stay humble.",
  "Zephaniah 3:17": "You are so loved that God delights over you — you're a joy, not a burden.",
  "Matthew 5:14": "You carry light — don't hide it; the world needs what you shine.",
  "Matthew 6:33": "Put first things first, and the rest of life falls into better order.",
  "Matthew 6:34": "Don't drown today in tomorrow's worries — handle today and let tomorrow wait.",
  "Matthew 11:28": "If you're exhausted and overloaded, there's a place to lay it down and rest.",
  "Matthew 19:26": "What feels impossible to you is not the final word — grace changes the math.",
  "Matthew 28:20": "You are never actually alone — that presence is with you always.",
  "John 3:16": "You are so loved that heaven gave everything so you'd never be lost.",
  "John 14:27": "Real peace is being offered to you — let your heart stop being troubled.",
  "John 16:33": "Trouble will come, but take heart — it doesn't get the last word.",
  "Romans 8:28": "Even the hard chapters are being woven into something good for you.",
  "Romans 8:31": "If God is on your side, no obstacle is bigger than that backing.",
  "Romans 8:38-39": "Nothing — not failure, fear, or the future — can cut you off from God's love.",
  "Romans 12:12": "Stay hopeful, stay patient, keep praying — that's how you get through.",
  "1 Corinthians 13:4": "Real love is patient and kind — that's the standard worth living by.",
  "1 Corinthians 13:13": "In the end, love is what lasts and what matters most.",
  "2 Corinthians 5:17": "You're not stuck as your old self — a fresh start is genuinely possible.",
  "2 Corinthians 12:9": "Your weak spots aren't disqualifying — grace shows up strongest there.",
  "Galatians 6:9": "Don't quit doing good — the harvest comes if you don't give up.",
  "Ephesians 2:10": "You were made for good things — your life has a designed purpose.",
  "Philippians 4:6": "Trade anxiety for honest prayer — hand over what you can't carry.",
  "Philippians 4:13": "You have access to a strength beyond your own for whatever you face.",
  "Philippians 4:19": "What you truly need will be met — you can loosen your grip on worry.",
  "Colossians 3:23": "Whatever you do, pour your heart into it — your work matters.",
  "Hebrews 11:1": "Faith is being sure of good you can't see yet — hope with backbone.",
  "James 1:5": "If you're unsure what to do, just ask — wisdom is given generously.",
  "1 Peter 5:7": "Whatever's weighing on you, hand it over — you are genuinely cared for.",
  "1 John 4:18": "Love, fully received, quiets fear — you don't have to be afraid to be loved.",
  "1 John 4:19": "You can love others because you were first loved — it starts with being loved.",
  "Revelation 21:4": "A day is coming with no more tears or pain — hold on to that hope.",

  // ---- Bhagavad Gita ----
  "Bhagavad Gita 2:14": "Good days and hard days both pass — ride them out without letting either own you.",
  "Bhagavad Gita 2:20": "The real you never dies; the deepest part of you is untouchable.",
  "Bhagavad Gita 2:47": "Do your best and release the outcome — your job is the effort, not the result.",
  "Bhagavad Gita 2:48": "Stay steady whether you win or lose — that balance is the real success.",
  "Bhagavad Gita 2:56": "Peace is staying calm when life shakes — not craving, not panicking.",
  "Bhagavad Gita 2:70": "Desires keep flowing in like rivers to the sea; peace is staying unshaken by them.",
  "Bhagavad Gita 3:8": "Don't just sit in worry — do your work; right action beats stuck inaction.",
  "Bhagavad Gita 3:21": "People watch how you live — your example quietly sets the standard.",
  "Bhagavad Gita 4:7": "Whenever things go dark, goodness rises again — light always returns.",
  "Bhagavad Gita 5:10": "Do your work, offer the results, and stay unstained — like a leaf on water.",
  "Bhagavad Gita 6:5": "Your mind can lift you or sink you — become its friend, not its victim.",
  "Bhagavad Gita 6:6": "Master your mind and it works for you; leave it unchecked and it works against you.",
  "Bhagavad Gita 6:19": "A steady mind is like a candle flame in still air — calm, bright, unwavering.",
  "Bhagavad Gita 6:35": "The restless mind can be tamed — with steady practice and letting go.",
  "Bhagavad Gita 9:26": "It's not the size of the offering that matters — it's the love behind it.",
  "Bhagavad Gita 12:15": "Be someone who neither rattles others nor is easily rattled — that's peace.",
  "Bhagavad Gita 18:66": "Let go of the weight you carry and surrender — you can stop being afraid.",
  "Bhagavad Gita 18:78": "Where effort and the divine work together, good things follow.",
  "Bhagavad Gita 2:3": "Don't collapse into discouragement — shake it off and stand back up; there's more in you than you think.",
  "Bhagavad Gita 2:11": "Grief is real, but the deepest part of us is never truly lost — the story is bigger than we can see.",
  "Bhagavad Gita 3:9": "Do your work as an offering, not as a grab for gain, and it stops weighing you down.",
  "Bhagavad Gita 3:35": "Be fully yourself, flaws and all, rather than a perfect copy of someone else.",
  "Bhagavad Gita 4:20": "Act freely by letting go of needing a certain result — peace isn't hiding in the outcome.",
  "Bhagavad Gita 4:42": "Cut through your own doubt and stand up — clarity comes when you stop second-guessing.",
  "Bhagavad Gita 5:29": "Knowing you're befriended by the divine in everyone, your heart can finally rest.",
  "Bhagavad Gita 6:17": "Balance in eating, rest and work quietly dissolves a lot of your suffering.",
  "Bhagavad Gita 6:26": "When your mind wanders off, don't scold it — gently, patiently bring it back.",
  "Bhagavad Gita 7:19": "It can take a long road, but the wise eventually come home to what's real.",
  "Bhagavad Gita 8:5": "What fills your heart at the end reflects what you loved all along — so love well now.",
  "Bhagavad Gita 9:31": "Turn your heart toward good and you won't be lost — steady peace follows.",
  "Bhagavad Gita 10:11": "Grace lights up the dark, confused places inside you — you're not left in the fog.",
  "Bhagavad Gita 11:33": "Step up and play your part — you're an instrument of something already in motion.",
  "Bhagavad Gita 12:12": "You don't have to figure it all out; letting go of the outcome brings peace right away.",
  "Bhagavad Gita 16:3": "Courage, forgiveness and freedom from pride — these are the marks of a life worth growing into.",
  "Bhagavad Gita 17:15": "Speak what's true, kind, and helpful — words like that heal instead of harm.",
  "Bhagavad Gita 18:48": "No work is ever perfect, so don't abandon your calling waiting for flawless — just begin.",
  "Bhagavad Gita 18:65": "Keep your heart set on the divine — you are dear, and you will find your way home.",

  // ---- Guru Granth Sahib ----
  "Mool Mantar": "One loving Creator is behind everything — beyond fear and hate, beyond time — and you can know that presence by grace, not by force.",
  "Japji Sahib": "Real riches aren't worn on the outside — carry contentment, humility and a quiet mind, and you're already wealthy.",
  "Guru Granth Sahib, Ang 62": "Knowing truth is good, but living it is higher — let your life, not just your words, be honest.",
  "Guru Granth Sahib, Ang 1245": "Earn honestly and share freely — that simple, generous way of living is the real path.",
  "Guru Granth Sahib (Guru Nanak)": "A humble heart full of love is worth more than all the wealth of kings.",
  "Guru Granth Sahib, Ang 1349": "One Light shines in everyone — so look past 'good' and 'bad' labels and see the sacred in every person.",
  "Guru Granth Sahib (Guru Tegh Bahadur)": "What you're searching for isn't far away — the Divine already lives within you; look inward.",
  "Guru Granth Sahib (Sukhmani Sahib)": "When you rest your mind on God, the worry and fear quietly lift.",
  "Japji Sahib (Pauri 25)": "Every good thing in your life is a gift — the more you notice and give thanks, the more blessing you find.",
  "Guru Granth Sahib, Ang 1427": "True strength is gentle: frighten no one, and don't live in fear of anyone.",

  // ---- Dhammapada ----
  "Dhammapada 1": "Your life follows your thoughts — tend your mind with care, and peace follows you like a shadow.",
  "Dhammapada 5": "You can't put out a fire with fire; only love can end resentment. Choose love — it's the way through.",
  "Dhammapada 183": "The whole path in one line: stop harming, do good, and clean up your own heart.",
  "Dhammapada 223": "Meet anger with kindness, greed with generosity, lies with truth — respond, don't react.",
  "Dhammapada 103": "The hardest, greatest victory isn't over others — it's mastering yourself.",
  "Dhammapada 165": "No one can clean your heart for you, and no one can stain it either — your choices are truly your own.",
  "Dhammapada 252": "It's easy to spot everyone else's flaws — turn that honest gaze gently on yourself.",
  "Dhammapada 276": "Teachers can point the way, but only you can take the steps — begin walking.",
  "Dhammapada 197": "You can stay light and free inside, even surrounded by anger — peace is a choice you keep making.",
  "Dhammapada 100": "One true, kind, peaceful word matters more than a flood of empty ones.",
  "Dhammapada 204": "Notice the real riches you already have: your health, a content heart, people you trust, and inner freedom.",

  // ---- Tripitaka (suttas) ----
  "Dhammacakkappavattana Sutta": "Suffering is real, it has causes, it can end — and there's a practical path out. You are not stuck.",
  "Metta Sutta": "Love others with the fierce, protective tenderness a mother has for her child — and let that love leave no one out.",
  "Karaniya Metta Sutta": "Let your kindness reach in every direction, holding no one outside it — a heart with no walls.",
  "Kalama Sutta": "Don't accept things just because you're told to — test them in your own life, and keep what is kind and true.",
  "Mahaparinibbana Sutta": "Everything changes and passes — so don't cling; live wholeheartedly and keep growing while you can.",
  "Samyutta Nikaya": "When you truly see that nothing stays the same, you stop grasping — and that letting-go is where peace begins.",
  "Sedaka Sutta": "Caring for yourself and caring for others aren't opposites — do one well and you strengthen the other.",
  "Anguttara Nikaya": "Gratitude is rare and precious — being genuinely thankful is a mark of a good and grounded heart.",
  // Timeless Wisdom
  "Marcus Aurelius": "You can't control what happens, but your mind is yours — and that is where your real power lives.",
  "Epictetus": "Events don't define you; your response does. The next choice is always yours to make.",
  "Seneca": "Most of our suffering is rehearsed in our heads for things that never come — so gently bring yourself back to now.",
  "Lao Tzu": "Don't be overwhelmed by the whole climb. Just take the one step in front of you, and then the next.",
  "Confucius": "Speed isn't the point — refusing to quit is. Keep going, however small the steps.",
  "Heraclitus": "Life is always moving, and so are you. Let yourself change; you were never meant to stay the same.",
  "Ralph Waldo Emerson": "You did what you could today — let it be enough, and let tomorrow start clean.",
  "Henry David Thoreau": "Move toward the life you actually want, one honest choice at a time — it's closer than it feels.",
  "Kahlil Gibran": "The hard things cracking you open are also how the light and the growth get in.",
  "Rabindranath Tagore": "Wanting change isn't enough — take the first real step, even if it's small and scary.",
  "Vincent van Gogh": "You don't need one grand act. A steady stack of small, faithful efforts becomes something great.",
  "William Blake": "Everything real once began as someone's imagination — so don't dismiss the dream stirring in you.",
  // Voices that changed things + world proverbs
  "Frederick Douglass": "Nothing worth having arrives without resistance — the difficulty isn't a sign you're failing, it's a sign you're moving.",
  "Booker T. Washington": "Don't measure your life by where you've landed. Measure it by what you had to climb over to get here.",
  "Theodore Roosevelt": "The people who criticise from the sidelines don't matter. What counts is that you're in it, trying, dust and all.",
  "Marie Curie": "Fear shrinks when you understand it. Face the thing you're afraid of by learning it, not avoiding it.",
  "Emily Dickinson": "Hope isn't loud or logical — it's the quiet thing inside you that keeps singing even when you've no reason to.",
  "Walt Whitman": "You don't need to justify your existence today. Being here, as you are, is already enough.",
  "Sun Tzu": "When everything is falling apart, something is also opening up. Look for the door the chaos just unlocked.",
  "Miyamoto Musashi": "Take yourself less seriously and the world more seriously — that's where clarity and skill are born.",
  "Swami Vivekananda": "Get up. Begin. And don't stop just because it's hard or slow — keep going until you arrive.",
  "Mahatma Gandhi": "If you feel lost, stop searching inward and go be useful to someone. You'll find yourself on the way.",
  "Florence Nightingale": "Excuses are comfortable and they cost you everything. Refuse to make them and refuse to accept them.",
  "Sojourner Truth": "The truth doesn't need you to defend it loudly. Live it, and it wins in the end.",
  "Abraham Lincoln": "You're allowed to be slow. You're just not allowed to go backwards. Progress counts at any pace.",
  "African proverb": "You can move quicker alone, but you'll go further with people beside you. Don't mistake speed for distance.",
  "Japanese proverb": "Falling isn't the failure — staying down is. Get up one more time than life knocks you over.",
  "Chinese proverb": "It's too late to have started sooner, and that's fine. The only useful moment to begin is this one.",
  "Persian proverb": "Whatever you're in right now — the pain or the joy — it moves. Hold both a little more lightly.",
  "Cherokee proverb": "Regret is expensive. Don't spend today paying for something you can no longer change.",
  "Irish blessing": "A hope spoken over you: that the way opens, the weather is kind, and you're carried when you're tired.",
  "Zulu proverb": "You are not a separate thing. Who you are was built by everyone who held you — and you build others in turn.",
  "Swedish proverb": "Say it out loud — the good and the hard. Joy grows when shared, and grief gets lighter.",
  "Turkish proverb": "It doesn't matter how much you've invested in the wrong path. Turning around isn't losing — it's the fastest way home.",
  // Wit that lifts
  "Mark Twain": "Aim for a life so full of laughter that even your wrinkles end up telling happy stories.",
  "Oscar Wilde": "You can be knee-deep in a hard season and still fix your eyes on something bright. Keep looking up.",
  "Elbert Hubbard": "None of us gets out of here unscathed, so loosen your grip and let some of life be light and funny.",
  "Josh Billings": "Pick one thing and cling to it like a stamp to a letter — persistence, not talent, is what gets you there.",
  "Benjamin Franklin": "Talk is cheap. One thing actually done says more than a hundred things nicely promised.",
  "Nicolas Chamfort": "A day with no laughter in it is the real waste. Find one thing to smile about today.",
  "Aesop": "No kindness is ever too small to matter. Every gentle thing you do lands somewhere and stays.",
  "On worry": "Fretting about what might go wrong just spends your peace early. Save it for the good things that are coming.",
  "On the comeback": "Setbacks make the best origin stories. Whatever knocked you down is only chapter one — keep reading.",
  "On small wins": "Getting up and trying on a hard day is not nothing — it's quietly brave. Give yourself the credit.",
  "On overthinking": "When your head is loud and crowded, you don't have to solve every thought. Breathe, and let a few of them go.",
  "On being human": "You're doing your best in a fragile, miraculous body. Treat yourself with the wonder you'd give any miracle.",
  "On today's forecast": "The doubts clouding your morning tend to burn off by afternoon. Odds are good you'll handle today just fine.",
  "On becoming": "The parts of you that feel unfinished aren't flaws — they're paint still drying on something beautiful.",
  // Torah / Tanakh
  "Genesis 1:1": "Everything that exists had a beginning and a Maker. You are part of something intended, not an accident.",
  "Genesis 2:3": "Even the Creator rested. Rest isn't laziness — it's holy, woven into the design of the world and of you.",
  "Genesis 12:2": "You are blessed so that you can be a blessing. What you've received is meant to flow through you to others.",
  "Genesis 50:20": "People may intend harm, but good can still be brought out of it. Your worst chapter can become someone's rescue.",
  "Exodus 3:14": "God's own name is simply 'I AM' — fully present, not a distant idea. Whatever you face, you're not facing it alone.",
  "Exodus 20:8": "Guard one day to rest and remember what matters. A life with no pause forgets its own soul.",
  "Leviticus 19:18": "Love your neighbour as yourself — the whole of goodness folded into one line. Start with the person nearest you.",
  "Leviticus 19:2": "You're called to holiness — not perfection, but a life set apart for good. You reflect something higher than the crowd.",
  "Numbers 6:24-26": "An ancient blessing spoken over you: to be kept, to be seen with a shining face, and to be given peace. Receive it today.",
  "Deuteronomy 6:4": "The Shema, the heartbeat of the faith: God is one. Life isn't scattered chaos; there is one Source holding it all together.",
  "Deuteronomy 8:3": "We don't live on bread alone. Your deepest hunger isn't physical — feed the spirit too.",
  "Deuteronomy 30:19": "Life and death are set before you; choose life. Every day you get to choose what you feed and where you go.",
  "Deuteronomy 31:8": "The One who goes before you will not fail or forsake you. You are led, and you are kept — so don't be afraid.",
  "Deuteronomy 33:27": "Underneath everything are the everlasting arms. However far you fall today, there's a floor of love beneath you.",
  // Tao Te Ching
  "Tao Te Ching 8": "Be like water: nourish, don't force, and be willing to take the low place. Strength that serves and yields outlasts strength that dominates.",
  "Tao Te Ching 9": "Don't overfill or oversharpen. Know when enough is enough — grasping for more spills what you already have.",
  "Tao Te Ching 22": "Yield and stay whole; bend and stay straight. When you stop competing, no one can compete with you.",
  "Tao Te Ching 24": "Straining to stand taller or move faster only unsteadies you. Slow down — forcing gets you nowhere.",
  "Tao Te Ching 33": "Knowing others is clever; knowing yourself is wisdom. The hardest and most worthwhile person to master is you.",
  "Tao Te Ching 43": "The softest thing overcomes the hardest. There's a quiet power in not forcing your way.",
  "Tao Te Ching 44": "Contentment is its own wealth. When you stop needing more, you already have everything.",
  "Tao Te Ching 63": "Handle the hard thing while it's still small and easy. Big troubles are just small ones we ignored.",
  "Tao Te Ching 64": "Great things grow from tiny beginnings. Don't despise the small first step — it's where everything starts.",
  "Tao Te Ching 76": "What is soft and flexible is alive; what is rigid is closer to death. Stay supple — bend so you don't break.",
  "Tao Te Ching 78": "Water wears down stone. Gentleness and patience overcome what force cannot. Soft is not weak.",
  "Tao Te Ching 81": "The more you give, the more you have. Generosity doesn't empty you — it enlarges you.",
  // More Bible
  "John 10:10": "You were made for more than merely getting by. Abundant life — full, deep, alive — is what's on offer.",
  "Romans 12:1": "Offer your whole ordinary life as something sacred. Worship isn't only singing; it's how you live your day.",
  "2 Corinthians 4:18": "What you can see is temporary; what you can't see lasts. Fix your eyes past the moment onto what endures.",
  "Colossians 3:15": "Let peace be the referee in your heart — and stay thankful. Gratitude and calm keep each other company.",
  "Hebrews 4:16": "You can come close, boldly, and find mercy and help exactly when you need it. You don't have to have it together first.",
  "1 Peter 5:10": "After a season of suffering, you will be restored, steadied and made strong. The pain is real, but it is not the end.",
  "Psalm 34:17": "When you cry out, you are heard, and rescue comes. Your voice doesn't vanish into the dark.",
  "Psalm 145:18": "God is near to everyone who calls. You don't have to shout across a distance — help is close.",
  "Isaiah 43:19": "Something new is springing up — a way through the wilderness, water in the desert. Watch for it; don't only look back.",
  "Galatians 2:20": "The old self can die and a new life live in its place. You are not stuck being who you were.",
  "Ephesians 6:10": "Your strength isn't only yours to manufacture — draw on a power greater than your own.",
  "1 John 3:1": "See how much you are loved — called a child of God. That's your identity before you achieve a single thing.",
  "Psalm 51:10": "You can ask for a clean heart and a fresh start — and receive one. Renewal is always available.",
  "Proverbs 16:9": "You make your plans, but your steps are guided. Hold your plans loosely; you're being led.",
};

// Warm fallback by topic so every verse shows a meaning while the batch grows.
const TOPIC_MEANING = {
  hope: "A gentle reminder to hold on — better is coming, and you have not been forgotten.",
  strength: "You carry more strength than you feel right now, and you don't have to summon it alone.",
  peace: "An invitation to set the worry down and let calm return to your heart.",
  love: "You are deeply loved, and love is the quiet gift you get to pass on today.",
  faith: "Trust the next step even before you can see the whole staircase.",
  guidance: "When the way is unclear, you're still being led — just take the next small step.",
  comfort: "Whatever you're carrying, you don't carry it alone; you are seen and held.",
  courage: "Be brave in the face of what scares you — you were made for this moment.",
  gratitude: "Notice one blessing today and let thankfulness change how the day feels.",
  wisdom: "Slow down and choose the gentle, true path over the loud, quick one.",
  protection: "You are watched over and kept; what comes against you doesn't get the last word.",
  joy: "Let something lift your heart today — joy is a quiet act of trust.",
  purpose: "You are here on purpose, for a purpose — your light matters.",
};

// ---- Teens (13–20) collection ----
Object.assign(MEANINGS, {
  "1 Timothy 4:12": "Your age is not a limit — how you live can lead. Start setting the example now.",
  "Jeremiah 1:5": "You were known and wanted before day one; your worth isn't something you have to earn.",
  "Psalm 56:3": "Fear can show up and you can still choose trust — the two can share the same breath.",
  "1 Corinthians 15:33": "Who you surround yourself with shapes who you become — choose your circle on purpose.",
  "Gita 2:47": "Pour yourself into the effort and release the outcome — do your part fully, let go of the score.",
  "Gita 6:5": "Your mind can be your best teammate or your worst critic — today, be on your own side.",
  "Gita 3:35": "A real version of you beats a flawless copy of someone else. Walk your own road.",
  "Dhammapada 81": "Compliments and criticism will both blow through — you don't have to move every time they do.",
  "Aristotle": "Everything wise starts with being honest about who you actually are.",
  "Plato": "The hardest opponent — and the best win — is your own impulses.",
  "Socrates": "A life you never question runs on autopilot. Pause and ask what you're really chasing.",
  "Romans 12:2": "You don't have to copy the crowd — a renewed mind lets you choose who you actually are.",
  "2 Timothy 1:7": "Fear isn't the voice to follow — you were made for power, love and a steady mind.",
  "On comparison": "Feeds show everyone's best 1% — comparing your whole self to it is a rigged game.",
  "On your worth": "You don't need an audience's approval to matter. You already do.",
  "On starting": "Waiting to feel ready can last forever; starting small breaks the spell.",
  "On failing": "One flop is data, not a verdict on who you are.",
  "On the scroll": "That 'everyone's ahead of me' feeling is manufactured — your timeline is your own.",
  "On discipline": "Small unglamorous choices today are a gift to the person you're becoming.",
  "On fitting in": "Standing out feels risky, but it's often just you being genuinely yourself.",
  "On hard days": "Your record against bad days is perfect — you're more durable than you feel.",
  "On slow progress": "Growth is boring up close and obvious in the rear-view. Trust the stacking.",
  "On self-talk": "Swap the inner critic for an inner coach — you listen to that voice all day.",
  "On being brave": "Courage and fear coexist; bravery is acting while the fear is still there.",
  "Psalm 37:23-24": "Stumbling isn't falling — you're held, so a wobble won't be the end of you.",
  "Isaiah 43:1": "You are known by name and claimed — you belong before you do anything to earn it.",
  "Psalm 46:5": "Steadiness lives inside you; morning always comes — you won't be shaken loose.",
  "Gita 6:19": "A settled mind is a superpower — steady inside, the noise outside can't rattle you.",
  "Gita 9:22": "Give your heart to what's good and you're looked after — you don't carry it all alone.",
  "Dhammapada 368": "Kindness is where restlessness finally quiets down — be gentle and find your calm.",
  "Louisa May Alcott": "You don't need calm seas — you're learning to handle any storm that comes.",
  "Leonardo da Vinci": "Curiosity never runs out — every new thing you learn makes you bigger, not tired.",
  "On your potential": "You haven't missed your moment; you're early, not late — the best is ahead.",
  "On growing up": "Nobody has the full map. Confidence comes from taking the next step, not having it all.",
  "On your voice": "Your perspective is needed — shrinking yourself helps no one; speak up.",
  "On bad days": "One rough day is a page, not the whole book — keep reading, it turns.",
  "On being unfinished": "You can be unfinished and wonderful at once — growth and worth aren't opposites.",
  "On not quitting": "The messy middle is where most people quit — outlast it and you've already won.",
  "On your dreams": "That big dream isn't a mistake — you were built for it, so chase it.",
  "On being young": "Right now isn't practice for later — this is the real thing, so show up fully.",
});

// ---- Coaches (motivation & leadership) collection ----
Object.assign(MEANINGS, {
  // Original coach-voice lines
  "The coach on showing up": "Greatness isn't handed to you — but you already have what it takes. The only missing piece is starting.",
  "Before the whistle": "You perform at the level you practised, not the level you hoped for. Prepare now so the big moment feels familiar.",
  "The halftime talk": "A bad first half isn't the ending — it's a checkpoint. You still have time and power to turn it around.",
  "On the team": "The best teams aren't the most gifted — they're the ones who carry each other and won't let anyone fail alone.",
  "The captain's rule": "You lead by example, not volume: first to the work, last to quit. People follow what you do.",
  "On the grind": "The unseen work — early mornings, quiet reps — is exactly what becomes visible when it counts.",
  "After the loss": "Losing hurts, but it teaches. Study it, keep your head up, and let it sharpen you for tomorrow.",
  "On building leaders": "Real leadership multiplies — you succeed by raising others up until they can stand on their own.",
  "On the bench": "Waiting isn't wasted. Stay sharp and supportive, so when your moment comes you seize it and keep it.",
  "The pre-game": "Fear tightens you up; trust sets you free. Lean on your preparation and your people, and hold nothing back.",
  "On practice": "Small habits become big performances. Treat the little things seriously and they'll carry you in the clutch.",
  "On pressure": "Feeling pressure means you're somewhere that matters. Slow your breath, and just do the next right thing.",
  "On the underdog": "Being counted out is freedom — no fear of losing what you never had, all the fire to prove what you can do.",
  "The fourth quarter": "When everyone's exhausted and quitting seems fair, that's exactly where the memorable ones dig in and finish.",
  "On the standard": "Your life rises to what you refuse to accept. Set a high bar and never let yourself slip beneath it.",
  "On carrying others": "True strength notices who's struggling and slows down to bring them along. Nobody gets left behind.",
  "On the long season": "Motivation comes and goes; discipline is the routine you keep anyway. Trust the process on the flat days.",
  "The final word": "The result doesn't own you — your response does. Who you become through it is the trophy that lasts.",
  "Pierre de Coubertin": "Winning matters less than how you compete. Fight well and give your best, and you've already succeeded.",
  // Marquee new scripture / Tao in this collection
  "1 Corinthians 9:24": "Everyone runs, but the prize goes to the one who runs with everything — so give it all.",
  "Philippians 3:14": "Stop replaying the past; fix your eyes ahead and press toward the goal in front of you.",
  "Ecclesiastes 4:9-10": "You go further together — when you stumble, a real teammate is there to pull you back up.",
  "Ecclesiastes 9:10": "Whatever's in front of you to do, do it wholeheartedly — half-effort is a wasted chance.",
  "Proverbs 24:16": "Falling isn't failing. What sets you apart is that you get back up, every single time.",
  "2 Chronicles 15:7": "Don't go weak now — the effort you're putting in is not wasted; the reward is coming.",
  "1 Corinthians 16:13": "Stay alert, hold your ground, be courageous, and be strong — don't back down from what's right.",
  "Nehemiah 6:3": "When you're doing something that matters, don't climb down for every distraction — protect the work.",
  "Mark 10:43-44": "The way up is service — the greatest leaders are the ones who serve their people first.",
  "Tao Te Ching 17": "The best leaders empower people so quietly that the team feels the victory is their own.",
  "Tao Te Ching 66": "To lead people, put yourself below them and serve — humility, not dominance, is what lifts you up.",
  "Tao Te Ching 68": "The strongest competitor stays calm and works with others — quiet control beats raw aggression.",
});

// ---- Spectrum batch (2026): Torah, Tao, Sikh, Buddhist, Gita & Bible ----
Object.assign(MEANINGS, {
  // Torah
  "Genesis 1:31": "The world was called good before anyone improved it — and so were you.",
  "Genesis 8:22": "Seasons keep turning whatever happens; the cold stretch you're in is scheduled to end.",
  "Genesis 9:13": "After the worst of it, a sign in the sky — a promise that this doesn't happen again.",
  "Genesis 15:1": "You don't have to be your own shield today; something larger stands in front of you.",
  "Genesis 28:16": "God was in the ordinary place all along — you just hadn't noticed yet.",
  "Genesis 31:49": "A blessing for distance: may you be watched over in the time you're apart.",
  "Genesis 45:5": "Stop punishing yourself for the past — good has already been made out of it.",
  "Exodus 15:2": "When strength comes back, it arrives as a song — relief has its own music.",
  "Exodus 23:20": "You're not finding the road alone; something goes ahead to keep you on it.",
  "Exodus 33:14": "The promise isn't an easier road. It's company on it, and rest at the end.",
  "Exodus 34:6": "This is who God says he is: patient, kind, and slow to give up on you.",
  "Leviticus 19:16": "When someone is in trouble, doing nothing is a choice. Don't make it.",
  "Leviticus 19:32": "Honour the old. They carry what you'll need and won't be here forever.",
  "Leviticus 19:34": "Treat the outsider as family — you know exactly what it feels like to be one.",
  "Leviticus 23:40": "Joy was commanded, not just permitted. Take the whole week of it.",
  "Leviticus 25:10": "Debts cancelled, people freed — everything gets a chance to start again.",
  "Deuteronomy 8:10": "Eat, be full, and say thank you. Gratitude is what keeps plenty from spoiling you.",
  "Deuteronomy 15:11": "There will always be someone in need. Open your hand anyway, and today.",
  "Deuteronomy 30:11": "What's asked of you is not beyond you. It's difficult, not impossible.",
  "Deuteronomy 30:14": "You already know what to do. It's in your mouth and your heart — now do it.",

  // Tao Te Ching
  "Tao Te Ching 1": "The realest things won't fit in words. Hold your explanations loosely.",
  "Tao Te Ching 11": "The empty part is the useful part — the space in your week is not wasted space.",
  "Tao Te Ching 12": "Too much input dulls you. Turn the volume down and your senses come back.",
  "Tao Te Ching 16": "Everything rises and returns. Get quiet enough to feel the current under it.",
  "Tao Te Ching 23": "No storm can keep up its own intensity. Neither can this one.",
  "Tao Te Ching 25": "Follow what's natural. Most of your strain comes from working against your grain.",
  "Tao Te Ching 29": "Some things can't be forced into shape. Grip tighter and you lose them faster.",
  "Tao Te Ching 34": "Real generosity doesn't keep a ledger or claim what it gave.",
  "Tao Te Ching 37": "Doing less, on purpose, is not the same as nothing getting done.",
  "Tao Te Ching 40": "Softness is a strategy, not a surrender — and going back is often going forward.",
  "Tao Te Ching 41": "Big things finish late. Being unfinished is not the same as being behind.",
  "Tao Te Ching 45": "Flawed and useful beats polished and stuck. Calm outlasts hurry.",
  "Tao Te Ching 46": "Discontent is the actual problem — not the thing you think you're missing.",
  "Tao Te Ching 47": "You don't need more distance or more information. Look closer to home.",
  "Tao Te Ching 48": "Growth adds; wisdom subtracts. Ask what you could put down this week.",
  "Tao Te Ching 56": "The people who really know tend to say the least. Be suspicious of the loudest voice.",
  "Tao Te Ching 67": "Compassion, restraint, and not needing to be first — these are strengths, not softness.",
  "Tao Te Ching 73": "Nothing you're carrying goes unseen, even when it feels completely unnoticed.",

  // Guru Granth Sahib
  "Japji Sahib (Pauri 1)": "You can't think or starve your way to truth. Live in step with it instead.",
  "Japji Sahib (Pauri 38)": "Character is forged, not found — patience and self-control do the shaping.",
  "Japji Sahib (Salok)": "Air, water and earth are raising you like parents. You're already being cared for.",
  "Guru Granth Sahib (Asa di Var)": "Written centuries ago, and still the plainest argument for a woman's equal worth.",
  "Guru Granth Sahib (Sukhmani Sahib IV)": "Remembering God is medicine — sorrow loses its grip where it's practised.",
  "Guru Granth Sahib (Sukhmani Sahib II)": "The highest path isn't complicated: keep God close, and do clean work.",
  "Guru Granth Sahib (Sukhmani Sahib III)": "Ego is the illness you didn't know you had. Humility was the cure all along.",
  "Guru Granth Sahib (Guru Arjan)": "Look anywhere today and he's there. Distance is what fear tells you, not what's true.",
  "Guru Granth Sahib (Guru Arjan II)": "If the world has withdrawn its support and respect, God has not.",
  "Guru Granth Sahib (Guru Arjan III)": "Ask for one thing above all: to remember him when things are good, not only when they're hard.",
  "Guru Granth Sahib (Guru Amar Das)": "You can't argue a restless mind into peace. Give it something true to rest on.",
  "Guru Granth Sahib (Guru Amar Das II)": "You're in a garden with a Gardener who tends every plant — including the slow one.",
  "Guru Granth Sahib (Guru Amar Das III)": "A prayer for a burning world: save it however you can, by whatever door it will open.",
  "Guru Granth Sahib (Anand Sahib)": "Joy arrived easily in the end, after all those years of trying hard for it.",
  "Guru Granth Sahib (Guru Ram Das)": "In the right company, sorrow comes to the door and simply doesn't come in.",
  "Guru Granth Sahib (Bhagat Kabir)": "The honest search for who's at fault ends up much closer to home.",
  "Guru Granth Sahib (Bhagat Ravidas)": "You don't need to travel to a holy place. A clean heart makes this one holy.",
  "Guru Granth Sahib (Bhagat Farid)": "Don't return the blow. Go home with your peace still intact.",
  "Guru Granth Sahib (Bhagat Farid II)": "Sweet words cost nothing and change everything. Try them where you'd usually snap.",
  "Guru Granth Sahib (Guru Tegh Bahadur II)": "Freedom is being unmoved by praise and blame alike — both are just weather.",
  "Guru Granth Sahib (Guru Nanak III)": "Today's small choices are seeds. You'll meet them again at harvest.",
  "Guru Granth Sahib (Guru Nanak II)": "However stained you feel, love washes it off faster than you can list the reasons it shouldn't.",

  // Dhammapada
  "Dhammapada 3": "Rehearsing the wrong done to you keeps the wound open. You can put the story down.",
  "Dhammapada 33": "A wandering mind isn't broken; it's raw material. It can be straightened with practice.",
  "Dhammapada 35": "The mind goes wherever it likes. Training it is the whole of the happiness.",
  "Dhammapada 80": "Everyone shapes something. The wise turn that skill on themselves.",
  "Dhammapada 96": "Real peace shows up in your voice and your actions, not just your mood.",
  "Dhammapada 121": "Small harms add up quietly. Nothing is too minor to matter.",
  "Dhammapada 122": "Small goods add up too — and nobody sees the jar filling until it's full.",
  "Dhammapada 129": "Everyone is as afraid as you are. Let that be the reason you go gently.",
  "Dhammapada 131": "Happiness taken at someone else's expense never actually arrives.",
  "Dhammapada 160": "Nobody is coming to save you from yourself — which is also the good news.",
  "Dhammapada 173": "An old wrong doesn't define you. New good is how you come out from behind the cloud.",
  "Dhammapada 178": "The first step matters more than any status you could win. Take it today.",
  "Dhammapada 182": "This life, this awareness, this chance — all three are rarer than they feel.",
  "Dhammapada 201": "Winning costs you something too. Step out of the contest and sleep well.",
  "Dhammapada 222": "Catching your anger mid-rise is real skill. That's the moment to be proud of.",
  "Dhammapada 239": "Change happens by the gram, not the tonne. Keep removing a little.",
  "Dhammapada 348": "Past, future, even the grip on now — let go of all three and you can cross.",

  // Tripitaka
  "Itivuttaka 27": "One kind heart outshines every other good thing you could do today.",
  "Udana 5.5": "Whatever door you came in by, the whole teaching tastes of one thing: freedom.",
  "Udana 8.3": "There is a way out of what's holding you. Its existence is the whole point.",
  "Sutta Nipata 1.8": "No deceiving, no despising, no quiet wish that someone gets what's coming.",
  "Kakacupama Sutta": "Other people's harshness doesn't get to decide what happens inside you.",
  "Sallatha Sutta": "The pain is the first arrow. The story you tell about it is the second — that one's optional.",
  "Dighajanu Sutta": "Effort, attention, good friends, and living within your means. That's the whole recipe.",
  "Upaddha Sutta": "Who you spend time with isn't part of the path. It basically is the path.",
  "Mangala Sutta": "The highest blessing turns out to be ordinary: family cared for, work done honestly.",
  "Mangala Sutta (II)": "Praise and criticism will both come. Being unshaken by either is the blessing.",
  "Dhajagga Sutta": "When fear rises, turn your mind to what's true and good — the grip loosens.",
  "Samyutta Nikaya 3.8": "You love yourself; so does everyone else. That's the whole argument against harm.",
  "Anguttara Nikaya 5.161": "The way out of resentment runs straight through kindness toward that same person.",
  "Vinaya, Mahavagga": "Care for whoever is suffering in front of you. That's where the sacred actually is.",
  "Anguttara Nikaya 2.4": "Some debts can't be settled, only honoured. Call your parents.",
  "Theragatha": "Shelter, warmth, a settled mind — you have enough. Let the sky do what it wants.",
  "Anguttara Nikaya 4.62": "Of all the comforts money buys, a clear conscience is the one worth the most.",
  "Anguttara Nikaya 8.6": "Praise, blame, gain, loss — eight winds that blow through every life. Stand still.",

  // Bhagavad Gita
  "Bhagavad Gita 2:15": "Steadiness through both the highs and the lows is the thing worth building.",
  "Bhagavad Gita 2:64": "Peace comes from not being yanked around by wanting and not-wanting.",
  "Bhagavad Gita 3:25": "Work as hard as the driven do — just without needing the outcome to prove you.",
  "Bhagavad Gita 4:39": "Trust plus discipline turns into understanding, and understanding into peace.",
  "Bhagavad Gita 5:21": "The happiness you keep chasing outside is already in the room with you.",
  "Bhagavad Gita 6:16": "Not too much, not too little. Most of wisdom is finding the middle setting.",
  "Bhagavad Gita 6:22": "Once you've found this, heavy sorrow can arrive and still not knock you over.",
  "Bhagavad Gita 17:20": "The purest giving is to someone who can never pay you back.",

  // Bible
  "Psalm 126:5": "What you're planting through tears now will come back as something worth singing about.",
  "Isaiah 55:12": "You'll come out of this — and the world will feel like it's celebrating with you.",
  "John 15:11": "This was said so your joy would be full, not merely tolerable.",
  "Habakkuk 3:18": "Joy that survives bad circumstances — chosen, not caused. That's the defiant kind.",
  "Isaiah 43:18": "Stop rereading the old chapter. It's not where the story is going.",
  "Ezekiel 36:26": "A heart that's gone hard can be made soft again. That's the offer.",
  "2 Corinthians 3:18": "You're being changed slowly, in the direction you're looking. Watch what you look at.",
  "Philippians 3:13": "One move: stop replaying what's behind and lean into what's ahead.",
  "Psalm 107:1": "Start with thank you. His love doesn't run out, so gratitude never runs short of material.",
  "James 1:17": "Every good thing came from somewhere, from someone who doesn't change his mind about you.",
  "Psalm 32:7": "You have somewhere to hide, and you'll come out of it with a song.",
  "Psalm 121:7-8": "Coming and going, today and after — you're watched over the whole way.",
});

function meaningFor(v) {
  return MEANINGS[v.ref] || TOPIC_MEANING[v.topic] ||
    "A reminder that you are seen, loved, and not alone today.";
}

// A ~1-minute spoken narration script (verse + plain meaning + a gentle close).
const _NARRATION_SOURCE = {
  Bible: "the Bible", Gita: "the Bhagavad Gita", Torah: "the Torah",
  Tao: "the Tao Te Ching", Sikh: "the Guru Granth Sahib",
  Dhammapada: "the Dhammapada", Tripitaka: "the Buddhist scriptures",
};
function narrationFor(v) {
  const src = _NARRATION_SOURCE[v.faith] || "today's reflection";
  return `Today's blessing, from ${src}. ${v.ref}. ` +
    `${v.text} ` +
    `In simple words: ${meaningFor(v)} ` +
    `So take a slow breath, and carry this with you today. ` +
    `You are seen. You are loved. May you be blessed.`;
}
