// sermons.js
// Original written devotionals / short sermons for EverVerse — each tied to a
// verse, ~2-3 minutes to read or listen. Reflections (interpretation), grown in
// batches. Body is an array of paragraphs; takeaway is the one line to carry.

const SERMONS = [
  {
    id: "worth-enough",
    title: "When You Feel You're Not Enough",
    faith: "Bible", theme: "comfort", verseRef: "Psalm 139:14",
    verseText: "I praise you because I am fearfully and wonderfully made; your works are wonderful.",
    body: [
      "There is a quiet lie that follows many of us through the day: that we are somehow not enough. Not talented enough, not far enough along, not good enough to be loved as we are. It whispers loudest when we compare our insides to everyone else's outsides.",
      "But listen to what this verse dares to say. You are not an accident or a rough draft. You were made — carefully, intentionally, wonderfully. The same creativity behind sunrises and oceans was at work when you were formed. Your worth was decided before you ever performed, achieved, or proved anything.",
      "That means you can stop auditioning for a love you already have. You can breathe. The pressure to be impressive can fall off your shoulders, because your value was never up for a vote.",
    ],
    takeaway: "You are not too much and not too little. You are wonderfully made — worth was never yours to earn.",
  },
  {
    id: "peace-in-storm",
    title: "Peace in the Middle of the Storm",
    faith: "Bible", theme: "peace", verseRef: "Philippians 4:6",
    verseText: "Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.",
    body: [
      "Anxiety loves to live in the future. It runs ahead of us into every 'what if,' rehearsing disasters that may never come. And the more we try to think our way out of worry, the tighter it grips.",
      "This verse offers a different door. It doesn't say 'have it all figured out.' It says: take the thing you're carrying and hand it over. Name it honestly in prayer. Peace doesn't come from controlling the outcome — it comes from trusting that you're not carrying it alone.",
      "You don't have to be calm to begin. You just have to be honest. Tell God the truth about your fear, and let a peace that doesn't quite make sense begin to guard your heart.",
    ],
    takeaway: "Trade the weight of worry for honest prayer — peace guards the heart that lets go.",
  },
  {
    id: "strength-weary",
    title: "Strength for the Weary",
    faith: "Bible", theme: "strength", verseRef: "Isaiah 40:31",
    verseText: "Those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary.",
    body: [
      "Tiredness isn't only physical. There's a deeper weariness that comes from carrying life for a long time — from being strong for everyone, from hoping and not yet seeing.",
      "Notice the promise here isn't that you'll never get tired. It's that your strength can be renewed — refilled from a source outside yourself. Eagles don't flap harder against the storm; they spread their wings and let the rising wind carry them.",
      "Maybe today the bravest, strongest thing you can do is stop striving and lean into that lift. Hope is not passive. It is how the weary rise again.",
    ],
    takeaway: "You don't have to manufacture strength — hope renews it. Spread your wings and rise.",
  },
  {
    id: "begin-again",
    title: "The Courage to Begin Again",
    faith: "Bible", theme: "hope", verseRef: "Lamentations 3:22-23",
    verseText: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
    body: [
      "Some of us are haunted by yesterday — a failure, a harsh word, a habit we swore we'd break and didn't. Shame tells us the story is over, that we've used up our chances.",
      "But mercy keeps its own calendar. This verse says compassion is new every morning — not stale, not rationed, not running low. Whatever yesterday held, morning brings a clean page.",
      "You are allowed to begin again. Not because you've earned it, but because love hasn't given up on you. Get up. Today is new, and so is the grace waiting in it.",
    ],
    takeaway: "Yesterday doesn't get the final word. Mercy is new this morning — begin again.",
  },
  {
    id: "love-casts-fear",
    title: "Love That Casts Out Fear",
    faith: "Bible", theme: "love", verseRef: "1 John 4:18",
    verseText: "There is no fear in love. But perfect love drives out fear.",
    body: [
      "So much of our fear is really a fear of not being loved — of being found out, left out, not measuring up. We build walls to stay safe, and the walls keep out the very love we ache for.",
      "This verse makes a bold claim: love and fear can't share the same seat. When you truly know you are loved — not for your performance but for your presence — fear loses its footing.",
      "Let yourself be loved today, fully and without earning it. And then pass it on. In a fearful world, choosing to love someone is a quiet act of courage that sets them free too.",
    ],
    takeaway: "You don't have to be afraid to be loved. Perfect love drives fear out — receive it, then give it.",
  },
  {
    id: "gita-do-your-part",
    title: "Do Your Part, Release the Rest",
    faith: "Gita", theme: "purpose", verseRef: "Bhagavad Gita 2:47",
    verseText: "You have a right to your actions, but never to the fruits of your actions. Let not the results be your motive.",
    body: [
      "We exhaust ourselves not by the work itself, but by clinging to how it must turn out. We tie our peace to results we cannot fully control — the outcome, the applause, the reward.",
      "The Gita offers a lighter way to live: give yourself fully to the action that is yours to do, and loosen your grip on the fruit. Plant the seed with love; you are not the one who makes it rain.",
      "This is not laziness — it is freedom. When your effort is sincere and your attachment to outcomes is released, you can act with your whole heart and still sleep in peace.",
    ],
    takeaway: "Pour your heart into the doing, and let go of the outcome. That is where peace lives.",
  },
  {
    id: "gita-befriend-mind",
    title: "Befriending Your Own Mind",
    faith: "Gita", theme: "strength", verseRef: "Bhagavad Gita 6:6",
    verseText: "For those who have conquered the mind, it is their friend. For those who have not, the mind works like an enemy.",
    body: [
      "The hardest person you'll deal with today may be yourself. The mind can be a cruel narrator — replaying mistakes, predicting failure, talking you out of your own peace.",
      "The Gita says this same mind can become your closest friend. Not by force, but by patient practice: noticing the runaway thought, and gently, again and again, guiding it back toward what is true and good.",
      "You are not your loudest thought. You are the quiet witness who can choose which thoughts to feed. Befriend your mind today, and it will begin to carry you instead of dragging you.",
    ],
    takeaway: "Your mind can be friend or enemy — train it gently, and it will start to lift you.",
  },
  {
    id: "gita-steady",
    title: "Steady in Pleasure and Pain",
    faith: "Gita", theme: "peace", verseRef: "Bhagavad Gita 2:48",
    verseText: "Perform your duty with an even mind, abandoning attachment to success and failure. Such evenness of mind is called yoga.",
    body: [
      "Life swings — a good day lifts us high, a hard day drops us low, and we ride the wave up and down, exhausted by our own reactions.",
      "The Gita points to a steadier center: an even mind that meets success without arrogance and failure without despair. This evenness isn't coldness; it's a deep, unshaken calm beneath the changing weather.",
      "You can't stop the waves. But you can learn to stand. Do the next right thing with a steady heart, and let neither the praise nor the setback move you off your center.",
    ],
    takeaway: "Meet the highs and lows with an even mind — steadiness is its own kind of strength.",
  },
  {
    id: "gita-light-returns",
    title: "The Light That Always Returns",
    faith: "Gita", theme: "hope", verseRef: "Bhagavad Gita 4:7",
    verseText: "Whenever righteousness declines and unrighteousness rises, I manifest myself.",
    body: [
      "When we look at the world — or at our own struggles — it can feel like the darkness is winning. Goodness looks fragile, and we wonder if it's worth it to keep doing right.",
      "The Gita answers with a promise older than time: whenever the dark grows heavy, the light rises to meet it. Goodness is never finally defeated; it returns, again and again, often through ordinary people who refuse to give up.",
      "Today, you can be one of those small returns of light. A kind word, an honest choice, a refusal to let bitterness win — this is how the darkness loses ground.",
    ],
    takeaway: "The light always returns — and today, you can be one of the ways it does.",
  },
  {
    id: "gita-surrender",
    title: "Surrender and Be Free",
    faith: "Gita", theme: "faith", verseRef: "Bhagavad Gita 18:66",
    verseText: "Abandon all varieties of duty and simply surrender unto me. I shall deliver you from all sin; do not fear.",
    body: [
      "We carry so much: the need to control, to fix, to hold everything together by sheer will. It feels responsible, but it slowly wears us thin.",
      "The Gita's final invitation is startlingly gentle: let go. Set down the impossible weight of managing it all, and surrender into something larger and kinder than your own effort.",
      "Surrender is not defeat — it is trust. It is opening your clenched hands and discovering they were never meant to hold the whole world. Do not fear. You can lay it down.",
    ],
    takeaway: "You were never meant to carry it all. Surrender the weight — and find you are free.",
  },
  {
    id: "sikh-earn-share",
    title: "Earn Honestly, Give Freely",
    faith: "Sikh", theme: "gold", verseRef: "Guru Granth Sahib, Ang 1245",
    verseText: "One who works for what they eat, and gives away some of what they have — O Nanak, they know the true path.",
    body: [
      "It's tempting to think holiness lives somewhere far off — in mountaintops or grand rituals. Guru Nanak points somewhere much closer: your daily work and your open hand.",
      "Earn your bread honestly, he says, and then share it. Not because you have extra, but because giving is how the heart stays soft and connected. A life of honest labour and quiet generosity is itself the spiritual path — no ladder to climb, just this, done with love.",
      "Today, you can walk that path in the smallest way: do your work with integrity, and give something away — your time, your help, a portion of what you have. That is where the sacred and the ordinary meet.",
    ],
    takeaway: "Honest work and an open hand — that ordinary, generous life is the true path.",
  },
  {
    id: "sikh-one-light",
    title: "The One Light in Everyone",
    faith: "Sikh", theme: "royal", verseRef: "Guru Granth Sahib, Ang 1349",
    verseText: "First, God created the Light; from that One Light came the whole creation. So who is good, and who is bad?",
    body: [
      "We spend so much energy sorting people — us and them, worthy and unworthy, insider and outsider. This verse gently dismantles all of it.",
      "If one Light gave rise to everyone, then that same Light is shining, however dimly, in the person who annoys you, the stranger, even the one you'd call an enemy. The labels we hang on each other are small; the shared source is vast.",
      "You don't have to agree with everyone to honour the Light in them. Today, try seeing one person you'd normally dismiss as a carrier of that same sacred flame. It changes how you speak, how you soften, how you love.",
    ],
    takeaway: "One Light shines in every person — so look past the labels and honour the sacred in all.",
  },
  {
    id: "dhp-guard-mind",
    title: "Tend the Garden of Your Mind",
    faith: "Dhammapada", theme: "night", verseRef: "Dhammapada 1",
    verseText: "Mind precedes all things; mind is their chief, they are mind-made. Speak or act with a pure mind, and happiness follows like a shadow that never leaves.",
    body: [
      "The Buddha begins the Dhammapada with a quietly radical idea: your life takes the shape of your thoughts. What you repeatedly dwell on becomes the mood you live in, the words you speak, the acts you do.",
      "This isn't about forcing positivity. It's about tending — noticing the seeds of bitterness or fear before they take over, and gently watering thoughts of kindness, patience and truth instead.",
      "You can't control every thought that arises, but you can choose which ones you feed. Feed the good ones today, and watch how peace begins to follow you around like a shadow that won't leave.",
    ],
    takeaway: "Your life follows your thoughts — tend your mind with care, and peace will follow you.",
  },
  {
    id: "dhp-conquer-self",
    title: "The Victory That Matters",
    faith: "Dhammapada", theme: "bold", verseRef: "Dhammapada 103",
    verseText: "Though one may conquer a thousand men in battle a thousand times, the one who conquers themselves is the greatest victor.",
    body: [
      "The world celebrates victories over others — the argument won, the rival beaten, the competitor left behind. The Buddha points to a harder, quieter conquest.",
      "The truly great victory is over yourself: over the flash of anger, the pull of craving, the habit you keep returning to. No one applauds these wins, and no one else even sees them — but they change everything.",
      "You don't have to win them all at once. Just the next one: the pause before the harsh reply, the choice to let go instead of grasp. Each small self-conquest is a greater triumph than any battle.",
    ],
    takeaway: "The greatest victory isn't over others — it's mastering yourself, one quiet choice at a time.",
  },
  {
    id: "trip-love-no-walls",
    title: "A Love Without Walls",
    faith: "Tripitaka", theme: "warm", verseRef: "Metta Sutta",
    verseText: "As a mother would protect her only child with her life, so let one cultivate boundless love toward all living beings.",
    body: [
      "We know how to love a few people fiercely — a child, a partner, a close friend. The Metta Sutta invites us to take that same protective tenderness and let it grow until it has no edges.",
      "Boundless love doesn't mean feeling warm about everyone all the time. It means genuinely wishing every being well — even those you'll never meet, even those who trouble you. It's a practice: quietly wishing safety, ease and happiness outward, ring by widening ring.",
      "Start small today. Wish yourself well, then someone you love, then someone neutral, then someone difficult, then all beings everywhere. A heart practised this way slowly loses its walls.",
    ],
    takeaway: "Take the fierce love you feel for a few, and let it grow until it leaves no one out.",
  },
  {
    id: "bible-invitation-rest",
    title: "The Invitation to Rest",
    faith: "Bible", theme: "comfort", verseRef: "Matthew 11:28",
    verseText: "Come to me, all you who are weary and burdened, and I will give you rest.",
    body: [
      "There is a particular kind of tired that sleep doesn't touch. It's the weariness of carrying — carrying worry, carrying other people, carrying the version of yourself you think you're supposed to be. You can rest all night and wake up still holding it.",
      "Notice who this invitation is for. Not the strong, not the finished, not the ones who have it together. It's addressed to the weary and the burdened — which, if we're honest, is most of us on most days. You don't have to qualify for this rest by getting better first. You qualify by being tired. That's the whole entry requirement.",
      "And notice what it doesn't ask. It doesn't say 'try harder' or 'carry it better.' It says come, and set it down. Rest here isn't a nap; it's permission to stop performing, stop proving, stop bracing. To be met exactly as you are, mid-mess, and told: you can put it down for a while.",
    ],
    takeaway: "You don't have to earn rest by getting your life in order. Come as you are, tired and all, and set it down.",
  },
  {
    id: "bible-through-valley",
    title: "Through the Valley",
    faith: "Bible", theme: "night", verseRef: "Psalm 23:4",
    verseText: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.",
    body: [
      "Read that first word again: through. Not around the valley, not over it, not somehow spared it — through. This ancient line makes no promise that you'll avoid the dark stretches of a life. It promises something harder and better: that you won't walk them alone.",
      "That's a very different kind of comfort than we usually want. We want the valley removed. What we're offered instead is company inside it — a presence that doesn't flinch at the dark, doesn't rush us, doesn't need us to pretend we're fine. The fear doesn't have to vanish for the courage to hold. 'I will fear no evil' isn't the absence of fear; it's fear that no longer runs the show, because you're not facing it by yourself.",
      "So if you're in a valley today, you don't have to manufacture a brave face. You just have to remember the preposition. You're going through. This is not where you live. And you are accompanied.",
    ],
    takeaway: "You're not asked to avoid the dark valleys — only to remember you walk them accompanied, and that you're walking through, not staying.",
  },
  {
    id: "bible-cant-see-path",
    title: "When You Can't See the Path",
    faith: "Bible", theme: "guidance", verseRef: "Proverbs 3:5-6",
    verseText: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.",
    body: [
      "Most of us want the whole map before we take a single step. We want certainty in advance — to know it works out before we risk anything. And so we stall, mistaking our anxiety for wisdom, calling our fear 'being careful.'",
      "This proverb gently loosens that grip. 'Lean not on your own understanding' isn't an insult to your mind; it's a mercy. It means you're allowed to not have it all figured out. You were never going to see the whole staircase from the bottom. You get the next step, lit just enough — and that has always been enough for the people who actually moved.",
      "The path gets made straight in the walking, not in the planning. Clarity is usually something you receive on the way, not before you leave. So take the next honest step you can see. Trust is not certainty; it's moving in the dark with your hand held.",
    ],
    takeaway: "You won't get the whole map. Take the next step you can see — the path straightens as you walk it, not before.",
  },
  {
    id: "gita-seasons-pass",
    title: "The Seasons Will Pass",
    faith: "Gita", theme: "peace", verseRef: "Bhagavad Gita 2:14",
    verseText: "The contact of the senses with the world brings fleeting cold and heat, pleasure and pain. These come and go and do not last. Endure them with patience.",
    body: [
      "The Gita says something here that sounds cold at first and turns out to be deeply kind: this feeling, whatever it is, is a season. It arrived. It will move. Cold and heat, pleasure and pain — they pass through you like weather through a sky. The sky is not the weather.",
      "When you're inside a hard feeling, it lies to you about its length. It insists it is permanent, that this is simply how things are now. This teaching hands you a quiet correction: it is fleeting. Not fake, not unimportant — fleeting. And knowing that changes how you carry it. You can endure almost anything you know is passing.",
      "The same is true of the good seasons, and that's the fuller wisdom. Hold the sweet moments a little more gently too — not gripping, not demanding they stay. When you stop clutching at what's temporary, you finally get to actually feel it, and then let it go without it taking you with it.",
    ],
    takeaway: "Whatever you feel today is weather, not climate. It came, it will move — endure the hard seasons and hold the sweet ones lightly.",
  },
  {
    id: "wisdom-one-thing-you-control",
    title: "The One Thing You Control",
    faith: "Wisdom", theme: "strength", verseRef: "Marcus Aurelius",
    verseText: "You have power over your mind — not outside events. Realize this, and you will find strength.",
    body: [
      "Almost all of our exhaustion comes from fighting a war we can't win: the war to control what happens. The traffic, the other person's mood, the outcome, the past, the weather of a whole day. We pour ourselves into the one place we have no authority, and then wonder why we feel so powerless.",
      "The Stoics offered a radical relief. Draw a line, they said. On one side: what you cannot control — events, results, other people. On the other: the only thing you actually govern — your own response. Marcus Aurelius, who ran an empire and could command almost anything, understood that even he ruled only one small territory: his own mind. And so do you.",
      "This isn't resignation; it's where strength lives. When you stop spending yourself on the uncontrollable, all that reclaimed energy goes into the one place it can do something — how you meet the moment. You can't choose the wave. You can choose whether to brace, or breathe, or begin. That choice, made a hundred times a day, is the whole of a steady life.",
    ],
    takeaway: "Stop spending yourself on what you can't control. Your response is the one territory you govern — and it's enough.",
  },
  {
    id: "wisdom-enough-before-you-begin",
    title: "Enough, Before You Begin",
    faith: "Wisdom", theme: "purpose", verseRef: "On being enough",
    verseText: "You are already enough. You were enough long before you achieved a single thing.",
    body: [
      "There's a quiet arithmetic most of us run without noticing: I'll be enough when — when I hit the goal, fix the flaw, earn the approval, arrive somewhere I'm not yet. It feels like motivation. It's actually a treadmill, and the finish line moves every time you near it.",
      "Here is the sentence that stops the treadmill: you were enough before any of it. Before the achievements, before the improving, before you proved a single thing to anyone. Your worth was never the prize at the end of your effort — it was the ground you were standing on the whole time. You've been trying to earn something you already own.",
      "And notice what this frees rather than what it excuses. When you stop working to become enough, you get to work from enough — lighter, braver, less afraid to fail, because failing can no longer touch your value. You still build, still grow, still reach. You just do it as someone already whole, not someone auditioning to be.",
    ],
    takeaway: "You're not working to become enough. You already are — so build from that ground instead of trying to earn it.",
  },
  {
    id: "wisdom-stand-up-again",
    title: "Stand Up Again",
    faith: "Wisdom", theme: "perseverance", verseRef: "Japanese proverb",
    verseText: "Fall seven times, stand up eight.",
    body: [
      "Count the numbers in that little proverb and you'll find the whole secret hidden in the arithmetic. Seven falls, eight stand-ups. The math only works if you were down before you started — if the very first thing was already getting up. It quietly assumes you will fall, and refuses to treat that as the story.",
      "We tend to believe the falling is the failure. It isn't. Everyone who has done anything worth doing has a long, unglamorous record of going down — the part nobody posts. The only failure the proverb recognises is the one where you stay down. Falling is just the cost of being in motion.",
      "So if today knocked you over, you haven't failed the test; you're simply between the seventh and the eighth. You don't need to rise dramatically, or feel ready, or have it figured out. You just need to get up one more time than life puts you down. That's not a talent. It's a decision, available again right now.",
    ],
    takeaway: "Falling isn't the failure — staying down is. You only have to stand up one more time than you fall.",
  },
  {
    id: "trip-path-out",
    title: "There Is a Way Through",
    faith: "Tripitaka", theme: "night", verseRef: "Dhammacakkappavattana Sutta",
    verseText: "There is suffering; there is a cause of suffering; there is an end of suffering; and there is a path that leads to its end.",
    body: [
      "The Buddha's very first teaching is startlingly honest: yes, there is suffering. He doesn't pretend life is painless. But he refuses to stop there.",
      "Suffering has causes — much of it in our grasping and resisting — and because it has causes, it can end. And there is a real, walkable path out. This is not despair; it is the most hopeful thing imaginable: you are not trapped.",
      "Whatever weighs on you today, hold both truths together — the pain is real, and it is not the end of the story. There is a way through, one honest step at a time.",
    ],
    takeaway: "Your pain is real — and it is not the whole story. There is a way through, step by step.",
  },
];

function sermonById(id) { return SERMONS.find((s) => s.id === id); }
