// verses.js
// Verified, curated verse database for the EverVerse daily engine.
// Bible verses use commonly-rendered English (public-domain / paraphrase).
// Gita verses use widely-accepted English renderings referenced by chapter:verse.
// Grow toward 365 in reviewed batches — the daily engine cycles through whatever exists.

const VERSE_DB = [
  // ---------------------------- BIBLE ----------------------------
  { faith: "Bible", ref: "Genesis 1:27", theme: "royal",  topic: "purpose",   text: "So God created mankind in his own image, in the image of God he created them." },
  { faith: "Bible", ref: "Exodus 14:14",  theme: "calm",   topic: "peace",     text: "The Lord will fight for you; you need only to be still." },
  { faith: "Bible", ref: "Deuteronomy 31:6", theme: "bold", topic: "courage",  text: "Be strong and courageous. Do not be afraid; for the Lord your God goes with you; he will never leave you nor forsake you." },
  { faith: "Bible", ref: "Joshua 1:9",    theme: "bold",   topic: "courage",   text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
  { faith: "Bible", ref: "1 Samuel 16:7", theme: "calm",   topic: "wisdom",    text: "The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart." },
  { faith: "Bible", ref: "Psalm 23:1",    theme: "calm",   topic: "comfort",   text: "The Lord is my shepherd; I shall not want." },
  { faith: "Bible", ref: "Psalm 23:4",    theme: "night",  topic: "comfort",   text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me." },
  { faith: "Bible", ref: "Psalm 27:1",    theme: "gold",   topic: "courage",   text: "The Lord is my light and my salvation—whom shall I fear?" },
  { faith: "Bible", ref: "Psalm 34:8",    theme: "warm",   topic: "gratitude", text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him." },
  { faith: "Bible", ref: "Psalm 37:4",    theme: "hope",   topic: "joy",       text: "Take delight in the Lord, and he will give you the desires of your heart." },
  { faith: "Bible", ref: "Psalm 46:1",    theme: "forest", topic: "protection",text: "God is our refuge and strength, an ever-present help in trouble." },
  { faith: "Bible", ref: "Psalm 46:10",   theme: "calm",   topic: "peace",     text: "Be still, and know that I am God." },
  { faith: "Bible", ref: "Psalm 91:1",    theme: "royal",  topic: "protection",text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty." },
  { faith: "Bible", ref: "Psalm 118:24",  theme: "hope",   topic: "joy",       text: "This is the day that the Lord has made; let us rejoice and be glad in it." },
  { faith: "Bible", ref: "Psalm 119:105", theme: "gold",   topic: "guidance",  text: "Your word is a lamp for my feet, a light on my path." },
  { faith: "Bible", ref: "Psalm 121:1-2", theme: "forest", topic: "protection",text: "I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord, the Maker of heaven and earth." },
  { faith: "Bible", ref: "Psalm 139:14",  theme: "warm",   topic: "purpose",   text: "I praise you because I am fearfully and wonderfully made; your works are wonderful." },
  { faith: "Bible", ref: "Proverbs 3:5-6",theme: "calm",   topic: "guidance",  text: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight." },
  { faith: "Bible", ref: "Proverbs 16:3", theme: "bold",   topic: "purpose",   text: "Commit to the Lord whatever you do, and he will establish your plans." },
  { faith: "Bible", ref: "Proverbs 17:22",theme: "hope",   topic: "joy",       text: "A cheerful heart is good medicine, but a crushed spirit dries up the bones." },
  { faith: "Bible", ref: "Proverbs 18:10",theme: "royal",  topic: "protection",text: "The name of the Lord is a fortified tower; the righteous run to it and are safe." },
  { faith: "Bible", ref: "Isaiah 26:3",   theme: "calm",   topic: "peace",     text: "You will keep in perfect peace those whose minds are steadfast, because they trust in you." },
  { faith: "Bible", ref: "Isaiah 40:31",  theme: "hope",   topic: "strength",  text: "Those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary." },
  { faith: "Bible", ref: "Isaiah 41:10",  theme: "bold",   topic: "strength",  text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you." },
  { faith: "Bible", ref: "Isaiah 43:2",   theme: "night",  topic: "protection",text: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you." },
  { faith: "Bible", ref: "Jeremiah 29:11",theme: "hope",   topic: "hope",      text: "For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { faith: "Bible", ref: "Lamentations 3:22-23", theme: "gold", topic: "gratitude", text: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness." },
  { faith: "Bible", ref: "Micah 6:8",     theme: "calm",   topic: "wisdom",    text: "Act justly, love mercy, and walk humbly with your God." },
  { faith: "Bible", ref: "Zephaniah 3:17",theme: "warm",   topic: "love",      text: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; he will rejoice over you with singing." },
  { faith: "Bible", ref: "Matthew 5:9",   theme: "calm",   topic: "peace",     text: "Blessed are the peacemakers, for they will be called children of God." },
  { faith: "Bible", ref: "Matthew 5:14",  theme: "gold",   topic: "purpose",   text: "You are the light of the world. A town built on a hill cannot be hidden." },
  { faith: "Bible", ref: "Matthew 6:33",  theme: "royal",  topic: "faith",     text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well." },
  { faith: "Bible", ref: "Matthew 6:34",  theme: "calm",   topic: "peace",     text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself." },
  { faith: "Bible", ref: "Matthew 11:28", theme: "forest", topic: "comfort",   text: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { faith: "Bible", ref: "Matthew 19:26", theme: "bold",   topic: "faith",     text: "With man this is impossible, but with God all things are possible." },
  { faith: "Bible", ref: "Mark 11:24",    theme: "hope",   topic: "faith",     text: "Whatever you ask for in prayer, believe that you have received it, and it will be yours." },
  { faith: "Bible", ref: "Luke 1:37",     theme: "royal",  topic: "faith",     text: "For nothing will be impossible with God." },
  { faith: "Bible", ref: "John 3:16",     theme: "warm",   topic: "love",      text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." },
  { faith: "Bible", ref: "John 8:12",     theme: "gold",   topic: "guidance",  text: "I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life." },
  { faith: "Bible", ref: "John 14:27",    theme: "calm",   topic: "peace",     text: "Peace I leave with you; my peace I give you. Do not let your hearts be troubled and do not be afraid." },
  { faith: "Bible", ref: "John 16:33",    theme: "bold",   topic: "courage",   text: "In this world you will have trouble. But take heart! I have overcome the world." },
  { faith: "Bible", ref: "Acts 20:35",    theme: "warm",   topic: "love",      text: "It is more blessed to give than to receive." },
  { faith: "Bible", ref: "Romans 5:8",    theme: "warm",   topic: "love",      text: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { faith: "Bible", ref: "Romans 8:28",   theme: "hope",   topic: "hope",      text: "And we know that in all things God works for the good of those who love him." },
  { faith: "Bible", ref: "Romans 12:2",   theme: "royal",  topic: "wisdom",    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind." },
  { faith: "Bible", ref: "Romans 15:13",  theme: "hope",   topic: "hope",      text: "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope." },
  { faith: "Bible", ref: "1 Corinthians 13:4", theme: "warm", topic: "love",   text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud." },
  { faith: "Bible", ref: "1 Corinthians 13:13", theme: "warm", topic: "love",  text: "And now these three remain: faith, hope and love. But the greatest of these is love." },
  { faith: "Bible", ref: "1 Corinthians 16:14", theme: "warm", topic: "love",  text: "Do everything in love." },
  { faith: "Bible", ref: "2 Corinthians 5:7", theme: "night", topic: "faith",  text: "For we live by faith, not by sight." },
  { faith: "Bible", ref: "2 Corinthians 12:9", theme: "bold", topic: "strength", text: "My grace is sufficient for you, for my power is made perfect in weakness." },
  { faith: "Bible", ref: "Galatians 6:9", theme: "gold",   topic: "strength",  text: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up." },
  { faith: "Bible", ref: "Ephesians 2:8", theme: "royal",  topic: "faith",     text: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God." },
  { faith: "Bible", ref: "Philippians 4:6", theme: "calm", topic: "peace",     text: "Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God." },
  { faith: "Bible", ref: "Philippians 4:13", theme: "bold", topic: "strength", text: "I can do all things through Christ who strengthens me." },
  { faith: "Bible", ref: "Colossians 3:23", theme: "gold", topic: "purpose",   text: "Whatever you do, work at it with all your heart, as working for the Lord." },
  { faith: "Bible", ref: "1 Thessalonians 5:16-18", theme: "hope", topic: "gratitude", text: "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you." },
  { faith: "Bible", ref: "2 Timothy 1:7", theme: "bold",   topic: "courage",   text: "For God has not given us a spirit of fear, but of power and of love and of a sound mind." },
  { faith: "Bible", ref: "Hebrews 11:1",  theme: "night",  topic: "faith",     text: "Now faith is confidence in what we hope for and assurance about what we do not see." },
  { faith: "Bible", ref: "Hebrews 13:8",  theme: "royal",  topic: "faith",     text: "Jesus Christ is the same yesterday and today and forever." },
  { faith: "Bible", ref: "James 1:2-3",   theme: "bold",   topic: "strength",  text: "Consider it pure joy whenever you face trials, because the testing of your faith produces perseverance." },
  { faith: "Bible", ref: "1 Peter 5:7",   theme: "calm",   topic: "comfort",   text: "Cast all your anxiety on him because he cares for you." },
  { faith: "Bible", ref: "1 John 4:18",   theme: "warm",   topic: "love",      text: "There is no fear in love. But perfect love drives out fear." },
  { faith: "Bible", ref: "1 John 4:19",   theme: "warm",   topic: "love",      text: "We love because he first loved us." },
  { faith: "Bible", ref: "Revelation 21:4", theme: "gold", topic: "comfort",   text: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain." },
  { faith: "Bible", ref: "Genesis 28:15",  theme: "forest", topic: "protection", text: "I am with you and will watch over you wherever you go, and I will bring you back to this land." },
  { faith: "Bible", ref: "Deuteronomy 6:5", theme: "warm",  topic: "love",      text: "Love the Lord your God with all your heart and with all your soul and with all your strength." },
  { faith: "Bible", ref: "1 Chronicles 16:11", theme: "gold", topic: "guidance", text: "Look to the Lord and his strength; seek his face always." },
  { faith: "Bible", ref: "1 Chronicles 16:34", theme: "hope", topic: "gratitude", text: "Give thanks to the Lord, for he is good; his love endures forever." },
  { faith: "Bible", ref: "Nehemiah 8:10",  theme: "hope",   topic: "joy",       text: "Do not grieve, for the joy of the Lord is your strength." },
  { faith: "Bible", ref: "Job 19:25",      theme: "royal",  topic: "faith",     text: "I know that my redeemer lives, and that in the end he will stand on the earth." },
  { faith: "Bible", ref: "Psalm 16:11",    theme: "gold",   topic: "joy",       text: "You make known to me the path of life; you will fill me with joy in your presence." },
  { faith: "Bible", ref: "Psalm 18:2",     theme: "bold",   topic: "protection",text: "The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge." },
  { faith: "Bible", ref: "Psalm 19:1",     theme: "night",  topic: "wisdom",    text: "The heavens declare the glory of God; the skies proclaim the work of his hands." },
  { faith: "Bible", ref: "Psalm 28:7",     theme: "bold",   topic: "strength",  text: "The Lord is my strength and my shield; my heart trusts in him, and he helps me." },
  { faith: "Bible", ref: "Psalm 30:5",     theme: "hope",   topic: "hope",      text: "Weeping may stay for the night, but rejoicing comes in the morning." },
  { faith: "Bible", ref: "Psalm 31:24",    theme: "bold",   topic: "courage",   text: "Be strong and take heart, all you who hope in the Lord." },
  { faith: "Bible", ref: "Psalm 34:18",    theme: "calm",   topic: "comfort",   text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit." },
  { faith: "Bible", ref: "Psalm 42:11",    theme: "hope",   topic: "hope",      text: "Why, my soul, are you downcast? Put your hope in God, for I will yet praise him, my Savior and my God." },
  { faith: "Bible", ref: "Psalm 55:22",    theme: "calm",   topic: "comfort",   text: "Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken." },
  { faith: "Bible", ref: "Psalm 62:1",     theme: "calm",   topic: "peace",     text: "Truly my soul finds rest in God; my salvation comes from him." },
  { faith: "Bible", ref: "Psalm 73:26",    theme: "bold",   topic: "strength",  text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever." },
  { faith: "Bible", ref: "Psalm 90:12",    theme: "royal",  topic: "wisdom",    text: "Teach us to number our days, that we may gain a heart of wisdom." },
  { faith: "Bible", ref: "Psalm 100:4",    theme: "gold",   topic: "gratitude", text: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name." },
  { faith: "Bible", ref: "Psalm 103:2",    theme: "gold",   topic: "gratitude", text: "Praise the Lord, my soul, and forget not all his benefits." },
  { faith: "Bible", ref: "Psalm 118:6",    theme: "bold",   topic: "courage",   text: "The Lord is with me; I will not be afraid. What can mere mortals do to me?" },
  { faith: "Bible", ref: "Psalm 143:8",    theme: "hope",   topic: "guidance",  text: "Let the morning bring me word of your unfailing love, for I have put my trust in you." },
  { faith: "Bible", ref: "Psalm 147:3",    theme: "calm",   topic: "comfort",   text: "He heals the brokenhearted and binds up their wounds." },
  { faith: "Bible", ref: "Proverbs 4:23",  theme: "forest", topic: "wisdom",    text: "Above all else, guard your heart, for everything you do flows from it." },
  { faith: "Bible", ref: "Proverbs 11:25", theme: "warm",   topic: "love",      text: "A generous person will prosper; whoever refreshes others will be refreshed." },
  { faith: "Bible", ref: "Proverbs 15:1",  theme: "calm",   topic: "wisdom",    text: "A gentle answer turns away wrath, but a harsh word stirs up anger." },
  { faith: "Bible", ref: "Proverbs 19:21", theme: "royal",  topic: "guidance",  text: "Many are the plans in a person's heart, but it is the Lord's purpose that prevails." },
  { faith: "Bible", ref: "Proverbs 27:17", theme: "bold",   topic: "love",      text: "As iron sharpens iron, so one person sharpens another." },
  { faith: "Bible", ref: "Ecclesiastes 3:1", theme: "forest", topic: "wisdom",  text: "There is a time for everything, and a season for every activity under the heavens." },
  { faith: "Bible", ref: "Isaiah 12:2",    theme: "hope",   topic: "faith",     text: "Surely God is my salvation; I will trust and not be afraid. The Lord is my strength and my defense." },
  { faith: "Bible", ref: "Isaiah 30:15",   theme: "calm",   topic: "peace",     text: "In repentance and rest is your salvation, in quietness and trust is your strength." },
  { faith: "Bible", ref: "Isaiah 40:8",    theme: "gold",   topic: "faith",     text: "The grass withers and the flowers fall, but the word of our God endures forever." },
  { faith: "Bible", ref: "Matthew 5:16",   theme: "gold",   topic: "purpose",   text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven." },
  { faith: "Bible", ref: "Matthew 7:7",    theme: "hope",   topic: "faith",     text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you." },
  { faith: "Bible", ref: "Matthew 28:20",  theme: "royal",  topic: "comfort",   text: "And surely I am with you always, to the very end of the age." },
  { faith: "Bible", ref: "Luke 6:31",      theme: "warm",   topic: "love",      text: "Do to others as you would have them do to you." },
  { faith: "Bible", ref: "John 13:34",     theme: "warm",   topic: "love",      text: "A new command I give you: Love one another. As I have loved you, so you must love one another." },
  { faith: "Bible", ref: "John 15:5",      theme: "forest", topic: "faith",     text: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit." },
  { faith: "Bible", ref: "Romans 8:31",    theme: "bold",   topic: "courage",   text: "What, then, shall we say in response to these things? If God is for us, who can be against us?" },
  { faith: "Bible", ref: "Romans 8:38-39", theme: "warm",   topic: "love",      text: "Neither death nor life, neither angels nor demons, neither the present nor the future, will be able to separate us from the love of God." },
  { faith: "Bible", ref: "Romans 12:12",   theme: "hope",   topic: "hope",      text: "Be joyful in hope, patient in affliction, faithful in prayer." },
  { faith: "Bible", ref: "Romans 12:21",   theme: "bold",   topic: "courage",   text: "Do not be overcome by evil, but overcome evil with good." },
  { faith: "Bible", ref: "1 Corinthians 15:58", theme: "bold", topic: "strength", text: "Stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because your labor is not in vain." },
  { faith: "Bible", ref: "2 Corinthians 5:17", theme: "hope", topic: "hope",    text: "If anyone is in Christ, the new creation has come: The old has gone, the new is here!" },
  { faith: "Bible", ref: "2 Corinthians 9:7", theme: "warm", topic: "gratitude", text: "Each of you should give what you have decided in your heart to give, for God loves a cheerful giver." },
  { faith: "Bible", ref: "Galatians 5:22-23", theme: "forest", topic: "love",   text: "The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control." },
  { faith: "Bible", ref: "Ephesians 2:10", theme: "royal",  topic: "purpose",   text: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do." },
  { faith: "Bible", ref: "Ephesians 3:20", theme: "bold",   topic: "faith",     text: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us." },
  { faith: "Bible", ref: "Ephesians 4:32", theme: "warm",   topic: "love",      text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you." },
  { faith: "Bible", ref: "Philippians 1:6", theme: "hope",  topic: "hope",      text: "He who began a good work in you will carry it on to completion until the day of Christ Jesus." },
  { faith: "Bible", ref: "Philippians 4:8", theme: "calm",  topic: "wisdom",    text: "Whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely—think about such things." },
  { faith: "Bible", ref: "Colossians 3:2", theme: "night",  topic: "wisdom",    text: "Set your minds on things above, not on earthly things." },
  { faith: "Bible", ref: "1 Thessalonians 5:11", theme: "warm", topic: "love",  text: "Therefore encourage one another and build each other up, just as in fact you are doing." },
  { faith: "Bible", ref: "Hebrews 12:1",   theme: "bold",   topic: "strength",  text: "Let us run with perseverance the race marked out for us, throwing off everything that hinders." },
  { faith: "Bible", ref: "Hebrews 12:2",   theme: "gold",   topic: "faith",     text: "Let us fix our eyes on Jesus, the pioneer and perfecter of faith." },
  { faith: "Bible", ref: "James 1:5",      theme: "royal",  topic: "wisdom",    text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you." },
  { faith: "Bible", ref: "James 4:8",      theme: "forest", topic: "faith",     text: "Come near to God and he will come near to you." },
  { faith: "Bible", ref: "1 Peter 4:8",    theme: "warm",   topic: "love",      text: "Above all, love each other deeply, because love covers over a multitude of sins." },
  { faith: "Bible", ref: "1 John 1:9",     theme: "calm",   topic: "comfort",   text: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us." },
  { faith: "Bible", ref: "1 John 4:7",     theme: "warm",   topic: "love",      text: "Dear friends, let us love one another, for love comes from God." },
  { faith: "Bible", ref: "Jude 1:24",      theme: "royal",  topic: "protection",text: "To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy." },

  // ------------------------ BHAGAVAD GITA ------------------------
  { faith: "Gita", ref: "Bhagavad Gita 2:14",  theme: "forest", topic: "wisdom",   text: "The contacts of the senses give rise to heat and cold, pleasure and pain. They come and go, impermanent. Endure them bravely." },
  { faith: "Gita", ref: "Bhagavad Gita 2:20",  theme: "night",  topic: "comfort",  text: "The soul is never born nor does it ever die; it is eternal, everlasting and primeval. It is not slain when the body is slain." },
  { faith: "Gita", ref: "Bhagavad Gita 2:23",  theme: "bold",   topic: "strength", text: "Weapons cannot cut the soul, fire cannot burn it, water cannot wet it, and wind cannot dry it." },
  { faith: "Gita", ref: "Bhagavad Gita 2:47",  theme: "royal",  topic: "purpose",  text: "You have a right to your actions, but never to the fruits of your actions. Let not the results be your motive." },
  { faith: "Gita", ref: "Bhagavad Gita 2:48",  theme: "calm",   topic: "peace",    text: "Perform your duty with an even mind, abandoning attachment to success and failure. Such evenness of mind is called yoga." },
  { faith: "Gita", ref: "Bhagavad Gita 2:50",  theme: "gold",   topic: "wisdom",   text: "One who has mastered the mind acts skillfully in this life. Therefore strive for yoga, for yoga is skill in action." },
  { faith: "Gita", ref: "Bhagavad Gita 2:70",  theme: "calm",   topic: "peace",    text: "As rivers flow into the ocean but cannot make the vast ocean overflow, so the wise are not moved by desires that enter them; they alone find peace." },
  { faith: "Gita", ref: "Bhagavad Gita 3:19",  theme: "bold",   topic: "purpose",  text: "Therefore, always perform your duty without attachment, for by working without attachment one attains the Supreme." },
  { faith: "Gita", ref: "Bhagavad Gita 3:21",  theme: "gold",   topic: "purpose",  text: "Whatever a great person does, others follow. Whatever standard they set, the world pursues." },
  { faith: "Gita", ref: "Bhagavad Gita 4:7",   theme: "royal",  topic: "faith",    text: "Whenever righteousness declines and unrighteousness rises, I manifest myself." },
  { faith: "Gita", ref: "Bhagavad Gita 5:10",  theme: "forest", topic: "wisdom",   text: "One who acts offering all actions to the Divine, abandoning attachment, is untouched by sin, as a lotus leaf is untouched by water." },
  { faith: "Gita", ref: "Bhagavad Gita 6:5",   theme: "bold",   topic: "strength", text: "Elevate yourself through the power of your own mind; do not degrade yourself. The mind can be your friend and also your enemy." },
  { faith: "Gita", ref: "Bhagavad Gita 6:6",   theme: "night",  topic: "wisdom",   text: "For those who have conquered the mind, it is their friend. For those who have not, the mind works like an enemy." },
  { faith: "Gita", ref: "Bhagavad Gita 6:19",  theme: "calm",   topic: "peace",    text: "As a lamp in a windless place does not flicker, so is the disciplined mind of one absorbed in the Self." },
  { faith: "Gita", ref: "Bhagavad Gita 6:30",  theme: "warm",   topic: "love",     text: "One who sees me everywhere and sees everything in me is never separated from me, nor am I ever separated from them." },
  { faith: "Gita", ref: "Bhagavad Gita 6:35",  theme: "forest", topic: "strength", text: "The mind is restless and hard to control, but it can be conquered through steady practice and detachment." },
  { faith: "Gita", ref: "Bhagavad Gita 9:22",  theme: "gold",   topic: "protection", text: "To those who worship me with devotion, ever united with me, I carry what they lack and preserve what they have." },
  { faith: "Gita", ref: "Bhagavad Gita 9:26",  theme: "warm",   topic: "gratitude", text: "Whoever offers me with devotion a leaf, a flower, a fruit, or water—that offering of love I accept." },
  { faith: "Gita", ref: "Bhagavad Gita 10:20", theme: "royal",  topic: "purpose",  text: "I am the Self seated in the hearts of all beings. I am the beginning, the middle, and the end of all." },
  { faith: "Gita", ref: "Bhagavad Gita 12:15", theme: "calm",   topic: "peace",    text: "One who does not disturb the world and is not disturbed by it, free from joy, envy, fear and anxiety—such a one is dear to me." },
  { faith: "Gita", ref: "Bhagavad Gita 15:7",  theme: "night",  topic: "purpose",  text: "The eternal soul in every being is a part of my own eternal Self." },
  { faith: "Gita", ref: "Bhagavad Gita 16:21", theme: "bold",   topic: "wisdom",   text: "Lust, anger and greed are the three gates to self-destruction. Therefore let them go." },
  { faith: "Gita", ref: "Bhagavad Gita 18:66", theme: "warm",   topic: "faith",    text: "Abandon all varieties of duty and simply surrender unto me. I shall deliver you from all sin; do not fear." },
  { faith: "Gita", ref: "Bhagavad Gita 18:78", theme: "gold",   topic: "hope",     text: "Wherever there is the Divine and the devoted soul acting together, there is prosperity, victory and righteousness." },
  { faith: "Gita", ref: "Bhagavad Gita 2:13",  theme: "night",  topic: "comfort",  text: "As the soul passes in this body from childhood to youth to old age, so it passes into another body at death. The wise are not deluded by this." },
  { faith: "Gita", ref: "Bhagavad Gita 2:22",  theme: "calm",   topic: "comfort",  text: "As a person casts off worn-out garments and puts on new ones, so the soul casts off worn-out bodies and enters new ones." },
  { faith: "Gita", ref: "Bhagavad Gita 2:38",  theme: "bold",   topic: "courage",  text: "Treating alike pleasure and pain, gain and loss, victory and defeat, engage in your duty. Thus you will incur no sin." },
  { faith: "Gita", ref: "Bhagavad Gita 2:40",  theme: "hope",   topic: "hope",     text: "On this path no effort is ever wasted, and no gain is ever reversed; even a little of this practice protects one from great fear." },
  { faith: "Gita", ref: "Bhagavad Gita 2:56",  theme: "calm",   topic: "peace",    text: "One whose mind is undisturbed by sorrow, who does not crave pleasures, and who is free from attachment, fear and anger is called a sage of steady wisdom." },
  { faith: "Gita", ref: "Bhagavad Gita 3:8",   theme: "bold",   topic: "purpose",  text: "Perform your prescribed duty, for action is better than inaction. Without action you cannot even maintain your body." },
  { faith: "Gita", ref: "Bhagavad Gita 3:30",  theme: "royal",  topic: "faith",    text: "Dedicating all your actions to the Divine, with your mind fixed on the Self, free from desire and selfishness, act without agitation." },
  { faith: "Gita", ref: "Bhagavad Gita 4:11",  theme: "warm",   topic: "love",     text: "In whatever way people surrender to me, I reward them accordingly. Everyone follows my path in all respects." },
  { faith: "Gita", ref: "Bhagavad Gita 4:18",  theme: "forest", topic: "wisdom",   text: "One who sees inaction in action, and action in inaction, is wise among people and united in all their actions." },
  { faith: "Gita", ref: "Bhagavad Gita 4:38",  theme: "gold",   topic: "wisdom",   text: "In this world there is nothing so purifying as knowledge. One perfected in yoga finds this within the Self in time." },
  { faith: "Gita", ref: "Bhagavad Gita 5:22",  theme: "night",  topic: "wisdom",   text: "The pleasures born of contact with the senses are sources of pain and have a beginning and an end. The wise do not delight in them." },
  { faith: "Gita", ref: "Bhagavad Gita 6:7",   theme: "calm",   topic: "peace",    text: "For one who has conquered the mind, the Supreme is already reached, for such a person has attained peace in cold and heat, joy and sorrow." },
  { faith: "Gita", ref: "Bhagavad Gita 6:29",  theme: "forest", topic: "love",     text: "The true yogi sees the Self in all beings and all beings in the Self; they see the same everywhere." },
  { faith: "Gita", ref: "Bhagavad Gita 6:32",  theme: "warm",   topic: "love",     text: "The perfect yogi is one who sees the true equality of all beings and responds to their joys and sorrows as their own." },
  { faith: "Gita", ref: "Bhagavad Gita 7:7",   theme: "royal",  topic: "faith",    text: "There is nothing higher than me. All that exists is strung on me like pearls on a thread." },
  { faith: "Gita", ref: "Bhagavad Gita 7:8",   theme: "calm",   topic: "purpose",  text: "I am the taste of water, the light of the sun and the moon, the sacred sound in the sacred texts, the sound in space, and the strength in all beings." },
  { faith: "Gita", ref: "Bhagavad Gita 8:7",   theme: "bold",   topic: "faith",    text: "Therefore, remember me at all times and do your duty. With mind and intellect fixed on me, you will surely come to me." },
  { faith: "Gita", ref: "Bhagavad Gita 10:10", theme: "gold",   topic: "guidance", text: "To those who are ever devoted and worship me with love, I give the understanding by which they come to me." },
  { faith: "Gita", ref: "Bhagavad Gita 9:27",  theme: "warm",   topic: "gratitude", text: "Whatever you do, whatever you eat, whatever you offer or give away, do it as an offering to me." },
  { faith: "Gita", ref: "Bhagavad Gita 9:29",  theme: "warm",   topic: "love",     text: "I am equally present in all beings; none is hateful or dear to me. But those who worship me with devotion are in me, and I am in them." },
  { faith: "Gita", ref: "Bhagavad Gita 9:34",  theme: "royal",  topic: "faith",    text: "Fix your mind on me, be devoted to me, worship me and bow to me. Thus united with me, you shall surely come to me." },
  { faith: "Gita", ref: "Bhagavad Gita 10:8",  theme: "night",  topic: "purpose",  text: "I am the source of all; from me everything proceeds. Knowing this, the wise worship me with all their heart." },
  { faith: "Gita", ref: "Bhagavad Gita 12:8",  theme: "calm",   topic: "faith",    text: "Fix your mind on me alone and rest your intellect in me; thereafter you shall live in me. Of this there is no doubt." },
  { faith: "Gita", ref: "Bhagavad Gita 12:13-14", theme: "warm", topic: "love",    text: "One who is free from hatred, friendly and compassionate to all, free from ego and even-minded in pleasure and pain, is dear to me." },
  { faith: "Gita", ref: "Bhagavad Gita 13:28", theme: "forest", topic: "wisdom",   text: "One who sees the Supreme dwelling equally in all beings does not harm the Self by the self, and so reaches the highest goal." },
  { faith: "Gita", ref: "Bhagavad Gita 14:27", theme: "gold",   topic: "peace",    text: "I am the foundation of the immortal and imperishable, of eternal righteousness, and of unending joy." },
  { faith: "Gita", ref: "Bhagavad Gita 15:15", theme: "royal",  topic: "guidance", text: "I am seated in the hearts of all beings; from me come memory, knowledge and understanding." },
  { faith: "Gita", ref: "Bhagavad Gita 17:3",  theme: "forest", topic: "faith",    text: "The faith of each person is shaped by their nature. A person is made of their faith; as their faith is, so are they." },
  { faith: "Gita", ref: "Bhagavad Gita 18:46", theme: "bold",   topic: "purpose",  text: "By worshipping the Divine through one's own work—the source from which all beings arise—a person attains perfection." },
  { faith: "Gita", ref: "Bhagavad Gita 18:58", theme: "bold",   topic: "courage",  text: "Fixing your mind on me, you shall overcome all obstacles by my grace. But if from self-will you will not listen, you will be lost." },
  { faith: "Gita", ref: "Bhagavad Gita 18:61", theme: "night",  topic: "guidance", text: "The Lord dwells in the hearts of all beings, guiding their movements by his power." },
  { faith: "Gita", ref: "Bhagavad Gita 2:3",   theme: "bold",   topic: "courage",  text: "Do not yield to weakness of heart, for it does not become you. Shake off this faint-heartedness and arise." },
  { faith: "Gita", ref: "Bhagavad Gita 2:11",  theme: "night",  topic: "comfort",  text: "The wise grieve neither for the living nor for the dead. There was never a time when we did not exist." },
  { faith: "Gita", ref: "Bhagavad Gita 3:9",   theme: "royal",  topic: "purpose",  text: "Work done as an offering to the Divine frees you; work done for selfish gain binds you. So act without attachment." },
  { faith: "Gita", ref: "Bhagavad Gita 3:35",  theme: "forest", topic: "purpose",  text: "It is better to do your own duty imperfectly than to do another's duty well." },
  { faith: "Gita", ref: "Bhagavad Gita 4:20",  theme: "calm",   topic: "peace",    text: "Abandoning attachment to the results of action, ever content and dependent on nothing, one is at peace even while fully engaged." },
  { faith: "Gita", ref: "Bhagavad Gita 4:42",  theme: "bold",   topic: "courage",  text: "Therefore, with the sword of knowledge cut away the doubt in your heart, and arise." },
  { faith: "Gita", ref: "Bhagavad Gita 5:29",  theme: "warm",   topic: "peace",    text: "Knowing me as the friend of every being, one attains lasting peace." },
  { faith: "Gita", ref: "Bhagavad Gita 6:17",  theme: "forest", topic: "wisdom",   text: "For one moderate in eating, rest, work and recreation, the practice of yoga becomes the destroyer of sorrow." },
  { faith: "Gita", ref: "Bhagavad Gita 6:26",  theme: "calm",   topic: "peace",    text: "Whenever the restless mind wanders away, gently bring it back again and again under control." },
  { faith: "Gita", ref: "Bhagavad Gita 7:19",  theme: "royal",  topic: "faith",    text: "After many births, the wise one takes refuge in me, seeing the Divine in all. Such a great soul is rare." },
  { faith: "Gita", ref: "Bhagavad Gita 8:5",   theme: "night",  topic: "faith",    text: "Whoever at the end leaves the body remembering me alone comes to my being. Of this there is no doubt." },
  { faith: "Gita", ref: "Bhagavad Gita 9:31",  theme: "gold",   topic: "protection", text: "My devotee is never lost. Quickly the heart turns to righteousness and finds lasting peace." },
  { faith: "Gita", ref: "Bhagavad Gita 10:11", theme: "gold",   topic: "guidance", text: "Out of compassion, I dwell in the heart and destroy the darkness of ignorance with the shining lamp of wisdom." },
  { faith: "Gita", ref: "Bhagavad Gita 11:33", theme: "bold",   topic: "courage",  text: "Therefore arise and win glory. Be the instrument, for the work is already set in motion." },
  { faith: "Gita", ref: "Bhagavad Gita 12:12", theme: "calm",   topic: "peace",    text: "Better than knowledge is meditation; and better still is letting go of the fruits of action, for peace follows at once." },
  { faith: "Gita", ref: "Bhagavad Gita 16:3",  theme: "forest", topic: "wisdom",   text: "Vigor, forgiveness, purity, and freedom from hatred and pride belong to one born for a noble nature." },
  { faith: "Gita", ref: "Bhagavad Gita 17:15", theme: "calm",   topic: "wisdom",   text: "Speech that is truthful, kind, beneficial, and does not disturb others is a discipline of the tongue." },
  { faith: "Gita", ref: "Bhagavad Gita 18:48", theme: "bold",   topic: "purpose",  text: "Do not abandon the work you are meant to do, even if flawed, for every effort has some imperfection, as fire has smoke." },
  { faith: "Gita", ref: "Bhagavad Gita 18:65", theme: "warm",   topic: "love",     text: "Fix your mind on me, be devoted to me, and you will surely come to me. This I promise, for you are dear to me." },

  // ------------------- SIKHISM · GURU GRANTH SAHIB -------------------
  { faith: "Sikh", ref: "Mool Mantar",  theme: "royal",  topic: "faith",   text: "There is One Creator, whose Name is Truth — fearless, without hatred, timeless and without form, beyond birth and death, known by the Guru's grace." },
  { faith: "Sikh", ref: "Japji Sahib",  theme: "calm",   topic: "wisdom",  text: "Let contentment be your earrings, humility your begging bowl, and meditation the ashes upon your body." },
  { faith: "Sikh", ref: "Guru Granth Sahib, Ang 62", theme: "forest", topic: "wisdom", text: "Truth is higher than everything; but higher still is truthful living." },
  { faith: "Sikh", ref: "Guru Granth Sahib, Ang 1245", theme: "gold", topic: "purpose", text: "One who works for what they eat, and gives away some of what they have — O Nanak, they know the true path." },
  { faith: "Sikh", ref: "Guru Granth Sahib (Guru Nanak)", theme: "warm", topic: "love", text: "Even kings and emperors with mountains of wealth cannot compare with an ant filled with the love of God." },
  { faith: "Sikh", ref: "Guru Granth Sahib, Ang 1349", theme: "royal", topic: "purpose", text: "First, God created the Light; from that One Light came the whole creation. So who is good, and who is bad?" },
  { faith: "Sikh", ref: "Guru Granth Sahib (Guru Tegh Bahadur)", theme: "night", topic: "guidance", text: "As fragrance dwells within the flower, and reflection within the mirror, so God dwells within you — seek Him in your own heart." },
  { faith: "Sikh", ref: "Guru Granth Sahib (Sukhmani Sahib)", theme: "calm", topic: "peace", text: "In the remembrance of God the mind is at peace, and every sorrow and fear departs." },
  { faith: "Sikh", ref: "Japji Sahib (Pauri 25)", theme: "hope", topic: "gratitude", text: "By His grace we receive every gift; the more we give thanks, the more there remains to give." },
  { faith: "Sikh", ref: "Guru Granth Sahib, Ang 1427", theme: "bold", topic: "courage", text: "One who frightens no one, and is not afraid of anyone — recognize that person as truly wise." },

  // --------------------- BUDDHISM · DHAMMAPADA ----------------------
  { faith: "Dhammapada", ref: "Dhammapada 1",   theme: "night",  topic: "wisdom",  text: "Mind precedes all things; mind is their chief, they are mind-made. Speak or act with a pure mind, and happiness follows like a shadow that never leaves." },
  { faith: "Dhammapada", ref: "Dhammapada 5",   theme: "calm",   topic: "peace",   text: "Hatred is never ended by hatred, but by love alone — this is an eternal law." },
  { faith: "Dhammapada", ref: "Dhammapada 183", theme: "forest", topic: "wisdom",  text: "To avoid all evil, to cultivate good, and to purify one's own mind — this is the teaching of the Awakened Ones." },
  { faith: "Dhammapada", ref: "Dhammapada 223", theme: "warm",   topic: "love",    text: "Conquer anger with kindness, evil with good, greed with generosity, and lies with truth." },
  { faith: "Dhammapada", ref: "Dhammapada 103", theme: "bold",   topic: "strength", text: "Though one may conquer a thousand men in battle a thousand times, the one who conquers themselves is the greatest victor." },
  { faith: "Dhammapada", ref: "Dhammapada 165", theme: "royal",  topic: "purpose", text: "By oneself is one purified; by oneself is one defiled. No one can purify another — purity and impurity depend on oneself." },
  { faith: "Dhammapada", ref: "Dhammapada 252", theme: "calm",   topic: "wisdom",  text: "The faults of others are easily seen; our own are hard to see." },
  { faith: "Dhammapada", ref: "Dhammapada 276", theme: "bold",   topic: "courage", text: "You yourselves must walk the path; the Awakened Ones only show the way." },
  { faith: "Dhammapada", ref: "Dhammapada 197", theme: "hope",   topic: "joy",     text: "Happily let us live, free from hatred among those who hate." },
  { faith: "Dhammapada", ref: "Dhammapada 100", theme: "calm",   topic: "peace",   text: "Better than a thousand empty words is one word that brings peace." },
  { faith: "Dhammapada", ref: "Dhammapada 204", theme: "gold",   topic: "gratitude", text: "Health is the greatest gift, contentment the greatest wealth, trust the finest kinship, and freedom the highest joy." },

  // -------------------- BUDDHISM · TRIPITAKA (SUTTAS) ---------------
  { faith: "Tripitaka", ref: "Dhammacakkappavattana Sutta", theme: "night", topic: "wisdom", text: "There is suffering; there is a cause of suffering; there is an end of suffering; and there is a path that leads to its end." },
  { faith: "Tripitaka", ref: "Metta Sutta", theme: "warm", topic: "love", text: "As a mother would protect her only child with her life, so let one cultivate boundless love toward all living beings." },
  { faith: "Tripitaka", ref: "Karaniya Metta Sutta", theme: "hope", topic: "love", text: "Let your love flow outward through the whole world — above, below, and all around — without limit and without ill will." },
  { faith: "Tripitaka", ref: "Kalama Sutta", theme: "bold", topic: "wisdom", text: "Do not believe merely because it is tradition or hearsay. When you know for yourselves that a thing is good and blameless, then take it up and live by it." },
  { faith: "Tripitaka", ref: "Mahaparinibbana Sutta", theme: "calm", topic: "comfort", text: "All things that arise must pass away. Therefore, strive on with diligence." },
  { faith: "Tripitaka", ref: "Samyutta Nikaya", theme: "forest", topic: "peace", text: "All conditioned things are impermanent; seeing this clearly with wisdom, one turns toward peace." },
  { faith: "Tripitaka", ref: "Sedaka Sutta", theme: "royal", topic: "guidance", text: "Protecting oneself, one protects others; protecting others, one protects oneself." },
  { faith: "Tripitaka", ref: "Anguttara Nikaya", theme: "gold", topic: "gratitude", text: "A person of integrity is grateful and thankful — such gratitude is rare and precious in this world." },

  // ---------------------- TIMELESS WISDOM ----------------------
  // Public-domain thinkers (wrote in English or ultra-standard renderings) + original EverVerse affirmations.
  { faith: "Wisdom", ref: "Marcus Aurelius", theme: "dusk",   topic: "strength",     text: "You have power over your mind — not outside events. Realize this, and you will find strength." },
  { faith: "Wisdom", ref: "Epictetus",       theme: "bold",   topic: "strength",     text: "It is not what happens to you, but how you react to it that matters." },
  { faith: "Wisdom", ref: "Seneca",          theme: "calm",   topic: "peace",        text: "We suffer more often in imagination than in reality." },
  { faith: "Wisdom", ref: "Lao Tzu",         theme: "moss",   topic: "purpose",      text: "A journey of a thousand miles begins with a single step." },
  { faith: "Wisdom", ref: "Confucius",       theme: "terra",  topic: "perseverance", text: "It does not matter how slowly you go, as long as you do not stop." },
  { faith: "Wisdom", ref: "Heraclitus",      theme: "forest", topic: "change",       text: "No one ever steps in the same river twice, for it is not the same river and they are not the same person." },
  { faith: "Wisdom", ref: "Ralph Waldo Emerson", theme: "calm", topic: "peace",      text: "Finish each day and be done with it. You have done what you could." },
  { faith: "Wisdom", ref: "Henry David Thoreau", theme: "sage", topic: "purpose",    text: "Go confidently in the direction of your dreams. Live the life you have imagined." },
  { faith: "Wisdom", ref: "Kahlil Gibran",   theme: "night",  topic: "hope",         text: "Your pain is the breaking of the shell that encloses your understanding." },
  { faith: "Wisdom", ref: "Rabindranath Tagore", theme: "harvest", topic: "courage", text: "You can't cross the sea merely by standing and staring at the water." },
  { faith: "Wisdom", ref: "Vincent van Gogh", theme: "gold",  topic: "purpose",      text: "Great things are not done by impulse, but by a series of small things brought together." },
  { faith: "Wisdom", ref: "William Blake",   theme: "royal",  topic: "hope",         text: "What is now proved was once only imagined." },
  // Original EverVerse affirmations (evocative refs double as titles)
  { faith: "Wisdom", ref: "On beginning again", theme: "dusk",  topic: "hope",     text: "You are allowed to begin again — today, this hour, this very breath." },
  { faith: "Wisdom", ref: "On being enough",    theme: "blush", topic: "purpose",  text: "You are already enough. You were enough long before you achieved a single thing." },
  { faith: "Wisdom", ref: "On this moment",     theme: "calm",  topic: "peace",    text: "Breathe. This moment is the only one asking anything of you." },
  { faith: "Wisdom", ref: "On patience",        theme: "moss",  topic: "perseverance", text: "Your pace is not your worth. Slow growth is still growth." },
  { faith: "Wisdom", ref: "On your strength",   theme: "terra", topic: "strength", text: "You have survived every hard day so far. That is not luck — that is you." },
  { faith: "Wisdom", ref: "On rest",            theme: "sand",  topic: "peace",    text: "Let today be gentle. You do not have to earn your rest." },
  { faith: "Wisdom", ref: "On hope",            theme: "gold",  topic: "hope",     text: "The light you are looking for is also looking for you." },
  { faith: "Wisdom", ref: "On self-kindness",   theme: "clay",  topic: "love",     text: "Be as kind to yourself as you would be to someone you love." },
  { faith: "Wisdom", ref: "On your path",       theme: "sage",  topic: "purpose",  text: "You are not behind. You are exactly where your story needs you to be." },
  { faith: "Wisdom", ref: "On courage",         theme: "harvest", topic: "courage", text: "One small brave thing today. That is all. That is enough." },
];

// Display names for each source/faith (the `faith` key → human label).
const FAITH_LABELS = {
  Bible: "Bible",
  Gita: "Bhagavad Gita",
  Sikh: "Guru Granth Sahib",
  Dhammapada: "Dhammapada",
  Tripitaka: "Tripitaka",
  Wisdom: "Timeless Wisdom",
};
function faithLabel(f) { return FAITH_LABELS[f] || f; }

// Background palettes keyed by theme (two-stop gradients + text/accent colors).
const THEME_PALETTES = {
  warm:  { name: "Sunrise",     stops: ["#ff8a5b", "#c1272d"], text: "#fff8f0", accent: "#ffe3c7" },
  calm:  { name: "Still Water", stops: ["#2c5f7c", "#0b3954"], text: "#eaf6ff", accent: "#bfe3f5" },
  bold:  { name: "Ember",       stops: ["#6a11cb", "#2575fc"], text: "#ffffff", accent: "#d9c8ff" },
  hope:  { name: "Dawn",        stops: ["#f6d365", "#fda085"], text: "#3a1d0e", accent: "#7a3b1e" },
  royal: { name: "Royal",       stops: ["#41295a", "#2f0743"], text: "#f3e9ff", accent: "#c9a9ff" },
  night: { name: "Midnight",    stops: ["#0f2027", "#203a43"], text: "#f5f5f5", accent: "#9fd0e0" },
  gold:  { name: "Gilded",      stops: ["#b78628", "#8a5a00"], text: "#fff9e8", accent: "#ffe9a8" },
  forest:{ name: "Grove",       stops: ["#134e5e", "#71b280"], text: "#f0fff4", accent: "#c9f0d8" },
  // Modern, IG-native palettes (2026): muted, contemporary, editorial.
  blush: { name: "Blush",       stops: ["#f3a7c4", "#b25a86"], text: "#fff5f9", accent: "#ffdcea" },
  sage:  { name: "Sage",        stops: ["#a3bd9c", "#4a6b57"], text: "#f4fbef", accent: "#dcefce" },
  dusk:  { name: "Dusk",        stops: ["#6b76c4", "#2c2c5e"], text: "#eef0ff", accent: "#c3ccff" },
  noir:  { name: "Noir",        stops: ["#33333a", "#0e0e13"], text: "#f4f4f7", accent: "#c9a9ff" },
  sand:  { name: "Sand",        stops: ["#efe3cf", "#d8bf9c"], text: "#4a3a26", accent: "#8a6a3c", light: true },
  // Earthy / nature palettes.
  terra: { name: "Terracotta",  stops: ["#c96f4a", "#7a3b28"], text: "#fff3ec", accent: "#f2c9a0" },
  moss:  { name: "Moss",        stops: ["#6b8f5a", "#2f4a2a"], text: "#f2f7ec", accent: "#cfe3b8" },
  clay:  { name: "Clay",        stops: ["#c98d76", "#7d4f42"], text: "#fdf1ec", accent: "#e8c3b2" },
  harvest:{ name: "Harvest",    stops: ["#e6c680", "#b8853a"], text: "#4a3416", accent: "#8a5f24", light: true },
};

// Target languages for the free MyMemory API (used in the Studio translator).
const LANGUAGES = [
  { code: "es", name: "Spanish" }, { code: "fr", name: "French" }, { code: "de", name: "German" },
  { code: "it", name: "Italian" }, { code: "pt", name: "Portuguese" }, { code: "nl", name: "Dutch" },
  { code: "ru", name: "Russian" }, { code: "uk", name: "Ukrainian" }, { code: "pl", name: "Polish" },
  { code: "ro", name: "Romanian" }, { code: "el", name: "Greek" }, { code: "tr", name: "Turkish" },
  { code: "sv", name: "Swedish" }, { code: "zh-CN", name: "Chinese (Simplified)" }, { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" }, { code: "hi", name: "Hindi" }, { code: "bn", name: "Bengali" },
  { code: "pa", name: "Punjabi" }, { code: "ta", name: "Tamil" }, { code: "te", name: "Telugu" },
  { code: "ur", name: "Urdu", rtl: true }, { code: "ar", name: "Arabic", rtl: true },
  { code: "fa", name: "Persian", rtl: true }, { code: "he", name: "Hebrew", rtl: true },
  { code: "id", name: "Indonesian" }, { code: "ms", name: "Malay" }, { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamese" }, { code: "sw", name: "Swahili" }, { code: "af", name: "Afrikaans" },
  { code: "tl", name: "Filipino" },
];

/* ---------------------------------------------------------------- */
/*  Daily selection engine                                          */
/* ---------------------------------------------------------------- */
// Deterministic: the same date always yields the same verse, and the
// sequence is scrambled so faiths/topics don't repeat back-to-back.
function dayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  return Math.floor(diff / 86400000); // 1..366
}

// A fixed coprime stride scrambles the order without needing storage.
function verseIndexForDate(date) {
  const n = VERSE_DB.length;
  const doy = dayOfYear(date);
  const yearOffset = date.getFullYear() % n; // rotate a little each year
  const stride = 37; // coprime-ish with typical n for good spread
  return ((doy * stride) + yearOffset) % n;
}

function verseForDate(date) {
  return VERSE_DB[verseIndexForDate(date)];
}
